-- This file is automatically generated, do not edit!
-- Image data (c) Grinding Gear Games

return {
	ddsCoords={
		["monster-categories_36_36_BC7.dds.zst"]={
			Beast=1,
			Construct=2,
			Demon=3,
			Eldritch=4,
			Humanoid=5,
			Undead=6
		}
	}
}