-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Minion Data
-- Monster data (c) Grinding Gear Games
--
local minions, mod = ...

minions["RaisedZombie"] = {
	name = "Raised Zombie",
	monsterTags = { "animal_claw_weapon", "flesh_armour", "is_unarmed", "medium_height", "melee", "physical_affinity", "Unarmed_onhit_audio", "undead", "very_slow_movement", "zombie", },
	life = 0.7,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.75,
	damageSpread = 0.3,
	attackTime = 1.25,
	attackRange = 9,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "One Hand Axe",
	limit = "ActiveZombieLimit",
	baseMovementSpeed = 16,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"MinionMeleeStep",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["SummonedRagingSpirit"] = {
	name = "Raging Spirit",
	monsterTags = { "bone_armour", "construct", "extra_extra_small_height", "fast_movement", "is_unarmed", "melee", "physical_affinity", "skeleton", "Unarmed_onhit_audio", "undead", },
	life = 0.25,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.7,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 12,
	accuracy = 1,
	critChance = 5,
	limit = "ActiveRagingSpiritLimit",
	baseMovementSpeed = 45,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Construct",
	spawnLocation = {
	},
	skillList = {
		"MinionMeleeStep",
	},
	modList = {
		mod("Speed", "MORE", 40, 1, 0), -- MonsterSummonedSkullFastAttack1 [active_skill_attack_speed_+%_final = 40]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["RaisedSkeletonSniper"] = {
	name = "Skeletal Sniper",
	monsterTags = { "bone_armour", "bones", "has_bow", "medium_movement", "physical_affinity", "puncturing_weapon", "ranged", "skeleton", "Stab_onhit_audio", "undead", },
	life = 0.55,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1.15,
	damageSpread = 0.3,
	attackTime = 1.5,
	attackRange = 80,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "Bow",
	limit = "ActiveSkeletonLimit",
	baseMovementSpeed = 37,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"MinionMeleeBow",
		"GasShotSkeletonSniperMinion",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_skeleton_minion [is_skeleton_minion = 1]
	},
}

minions["RaisedSkeletonBrute"] = {
	name = "Skeletal Brute",
	monsterTags = { "2HBluntMetal_onhit_audio", "bone_armour", "bones", "fast_movement", "has_one_hand_sword", "has_one_handed_melee", "medium_height", "melee", "not_dex", "not_int", "physical_affinity", "skeleton", "slashing_weapon", "undead", },
	life = 1.2,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.7,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 2,
	damageSpread = 0.3,
	attackTime = 1.75,
	attackRange = 16,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "Two Hand Mace",
	limit = "ActiveSkeletonLimit",
	baseMovementSpeed = 42,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"MinionMeleeStep",
		"BoneshatterBruteMinion",
		"ShatteringRoarSkeletalBruteMinion",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_skeleton_minion [is_skeleton_minion = 1]
		-- melee_conditional_step_distance [melee_conditional_step_distance = 14]
		mod("EnemyHeavyStunBuildup", "MORE", 50, 0, 0), -- active_skill_hit_damage_stun_multiplier_+%_final [active_skill_hit_damage_stun_multiplier_+%_final = 50]
	},
}

minions["RaisedSkeletonStormMage"] = {
	name = "Skeletal Storm Mage",
	monsterTags = { "bone_armour", "bones", "caster", "is_unarmed", "lightning_affinity", "medium_height", "medium_movement", "not_dex", "not_str", "ranged", "skeleton", "slashing_weapon", "Unarmed_onhit_audio", "undead", },
	life = 0.53,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.15,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 50,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 50,
	companionChaosResist = 0,
	damage = 0.65,
	damageSpread = 0.3,
	attackTime = 1,
	attackRange = 80,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "Staff",
	limit = "ActiveSkeletonLimit",
	baseMovementSpeed = 37,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"ArcSkeletonMageMinion",
		"DeathStormSkeletonStormMageMinion",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_skeleton_minion [is_skeleton_minion = 1]
	},
}

minions["RaisedSkeletonFrostMage"] = {
	name = "Skeletal Frost Mage",
	monsterTags = { "bone_armour", "bones", "caster", "cold_affinity", "is_unarmed", "medium_height", "medium_movement", "not_dex", "not_str", "ranged", "skeleton", "slashing_weapon", "Unarmed_onhit_audio", "undead", },
	life = 0.53,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.15,
	fireResist = 0,
	coldResist = 50,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 50,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.6,
	damageSpread = 0.3,
	attackTime = 1,
	attackRange = 80,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "None",
	limit = "ActiveSkeletonLimit",
	baseMovementSpeed = 37,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"FrostBoltSkeletonMageMinion",
		"IceArmourSkeletonMageMinion",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_skeleton_minion [is_skeleton_minion = 1]
	},
}

minions["RaisedSkeletonCleric"] = {
	name = "Skeletal Cleric",
	monsterTags = { "bone_armour", "bones", "caster", "fire_affinity", "is_unarmed", "medium_height", "medium_movement", "not_dex", "not_str", "ranged", "skeleton", "slashing_weapon", "Unarmed_onhit_audio", "undead", },
	life = 0.53,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.15,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.65,
	damageSpread = 0.3,
	attackTime = 1,
	attackRange = 80,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "One Hand Mace",
	limit = "ActiveSkeletonLimit",
	baseMovementSpeed = 37,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"HealSkeletonClericMinion",
		"ResurrectSkeletonClericMinion",
		"DoLiterallyNothing",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_skeleton_minion [is_skeleton_minion = 1]
	},
}

minions["RaisedSkeletonArsonist"] = {
	name = "Skeletal Arsonist",
	monsterTags = { "bone_armour", "bones", "caster", "fire_affinity", "is_unarmed", "medium_height", "medium_movement", "not_dex", "not_str", "ranged", "skeleton", "slashing_weapon", "Unarmed_onhit_audio", "undead", },
	life = 0.55,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.1,
	fireResist = 50,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 50,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.7,
	damageSpread = 0.3,
	attackTime = 1,
	attackRange = 80,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "None",
	limit = "ActiveSkeletonLimit",
	baseMovementSpeed = 37,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"FireBombSkeletonMinion",
		"DestructiveLinkSkeletonBombadierMinion",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_skeleton_minion [is_skeleton_minion = 1]
		-- strafe_distance_+% [strafe_distance_+% = -40]
	},
}

minions["RaisedSkeletonReaver"] = {
	name = "Skeletal Reaver",
	monsterTags = { "1HAxe_onhit_audio", "bone_armour", "bones", "fast_movement", "has_one_hand_sword", "has_one_handed_melee", "medium_height", "melee", "not_dex", "not_int", "physical_affinity", "skeleton", "slashing_weapon", "undead", },
	life = 0.7,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.46,
	damageSpread = 0.3,
	attackTime = 0.83,
	attackRange = 14,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "One Hand Axe",
	weaponType2 = "One Hand Axe",
	limit = "ActiveSkeletonLimit",
	baseMovementSpeed = 42,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"MinionMeleeStep",
		"EnrageSkeletonReaverMinion",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_skeleton_minion [is_skeleton_minion = 1]
	},
}

minions["RaisedSkeletonWarriors"] = {
	name = "Skeletal Warrior",
	monsterTags = { "1HSword_onhit_audio", "bone_armour", "bones", "fast_movement", "has_one_hand_sword", "has_one_handed_melee", "medium_height", "melee", "not_dex", "not_int", "physical_affinity", "skeleton", "slashing_weapon", "undead", },
	life = 0.88,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.5,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.7,
	damageSpread = 0.3,
	attackTime = 1,
	attackRange = 12,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "One Hand Sword",
	weaponType2 = "Shield",
	limit = "ActiveSkeletonLimit",
	baseMovementSpeed = 42,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"MinionMeleeStep",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		mod("BlockChance", "BASE", 30, 0, 0), -- SkeletonWarriorPlayerMinionBlockChance [monster_base_block_% = 30]
		mod("BlockChanceMax", "BASE", 0, 0, 0), -- SkeletonWarriorPlayerMinionBlockChance [additional_maximum_block_% = 0]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_skeleton_minion [is_skeleton_minion = 1]
	},
}

minions["SummonedHellhound"] = {
	name = "Infernal Hound",
	monsterTags = { "beast", "demon", "medium_movement", "not_int", "red_blood", "Unarmed_onhit_audio", },
	life = 0.88,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.5,
	evasion = 0.5,
	fireResist = 50,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 50,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1.25,
	damageSpread = 0.3,
	attackTime = 0.75,
	attackRange = 10,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 37,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Demon",
	spawnLocation = {
	},
	skillList = {
		"MinionMelee",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["AncestralSpiritTurtle"] = {
	name = "Ancestral Spirit Turtle",
	monsterTags = { "beast", "Beast_onhit_audio", "bludgeoning_weapon", "has_one_hand_mace", "has_one_handed_melee", "light_armour", "medium_height", "melee", "not_dex", "not_int", "physical_affinity", "reptile_beast", "very_slow_movement", },
	life = 1.3,
	baseDamageIgnoresAttackSpeed = true,
	armour = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 15,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 9,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"MeleeAtAnimationSpeed",
		"ABTTTortoiseTotemBubble",
	},
	modList = {
		-- MonsterCannotBeSlowed [action_speed_cannot_be_reduced_below_base = 1]
		-- MonsterCannotBeSlowed [movement_speed_cannot_be_reduced_below_base = 1]
		mod("StunImmune", "FLAG", 1, 0, 0), -- MonsterCannotBeStunned1 [base_cannot_be_stunned = 1]
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["AncestralSpiritHulk"] = {
	name = "Ancestral Jade Hulk",
	monsterTags = { "beast", "Beast_onhit_audio", "bludgeoning_weapon", "has_one_hand_mace", "has_one_handed_melee", "light_armour", "mammal_beast", "medium_height", "melee", "not_dex", "not_int", "physical_affinity", "slow_movement", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.7,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1.8,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 14,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 27,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"MeleeAtAnimationSpeed",
		"DTTAncestralJadeHulkLeapSlam",
		"GAAncestralJadeHulkLeapImpact",
		"TCAncestralLeagueKaruiHulk",
		"GAAncestralLeagueKaruiHulkCharge",
		"EGJadeHulkWarcryBuff",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["AncestralSpiritCaster"] = {
	name = "Ancestral Jadecaster",
	monsterTags = { "bludgeoning_weapon", "has_one_hand_mace", "has_one_handed_melee", "human", "humanoid", "karui", "light_armour", "medium_height", "medium_movement", "melee", "not_dex", "not_str", "physical_affinity", "ranged", "Unarmed_onhit_audio", },
	life = 0.53,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 14,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 32,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Humanoid",
	spawnLocation = {
	},
	skillList = {
		"MeleeAtAnimationSpeed",
		"MPSAncestralTotemSpiritSoulCasterProjectile",
		"EASAncestralEncaseEnemy",
		"GSAncestralJadePrison",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["AncestralSpiritWarhorn"] = {
	name = "Ancestral Warhorn",
	monsterTags = { "2HBluntWood_onhit_audio", "bludgeoning_weapon", "has_one_hand_mace", "has_one_handed_melee", "human", "humanoid", "karui", "light_armour", "medium_height", "melee", "not_int", "physical_affinity", "very_slow_movement", },
	life = 0.75,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.35,
	evasion = 0.15,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 27,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 13,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Humanoid",
	spawnLocation = {
	},
	skillList = {
		"MeleeAtAnimationSpeed",
		"EGTotemSpiritJadeHornBlow",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["UnearthBoneConstruct"] = {
	name = "Bone Crawler",
	monsterTags = { "bones", "medium_movement", "MonsterStab_onhit_audio", "skeleton", "undead", },
	life = 0.35,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.75,
	damageSpread = 0.3,
	attackTime = 1.06,
	attackRange = 12,
	accuracy = 1,
	critChance = 5,
	limit = "ActiveUnearthBoneConstructLimit",
	baseMovementSpeed = 37,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Undead",
	spawnLocation = {
	},
	skillList = {
		"MinionMelee",
		"DATTBoneConstructPlayerSummoned",
		"GABoneConstructPlayerSummoned",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		mod("StunDuration", "OVERRIDE", 2.93, 0, 0), -- set_base_heavy_stun_duration_ms [set_base_heavy_stun_duration_ms = 2930]
	},
}

minions["SummonedRhoa"] = {
	name = "Rhoa Companion",
	monsterTags = { "beast", "fast_movement", "mammal_beast", "MonsterBlunt_onhit_audio", "not_int", "red_blood", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.5,
	evasion = 0.5,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.23,
	attackRange = 16,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 37,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"MinionMelee",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- MonsterIgnoreActorScaleFromStats [ignore_actor_scale_from_stats = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- set_has_quadruped_head_control_while_turning [set_has_quadruped_head_control_while_turning = 1]
		-- set_quadruped_head_turn_duration_ms [set_quadruped_head_turn_duration_ms = 200]
		-- no_blood_on_death [no_blood_on_death = 1]
	},
}

minions["ManifestWeapon"] = {
	name = "Animated Weapon",
	monsterTags = { "construct", "fast_movement", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1,
	damageSpread = 0,
	attackTime = 1,
	attackRange = 10,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 42,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Construct",
	spawnLocation = {
	},
	skillList = {
		"MinionMelee",
		"GAAnimateWeaponMaceSlam",
		"DTTAnimateWeaponSpearDashStab",
		"DTTAnimateWeaponSpearDashStabImpact",
		"GAAnimateWeaponQuarterstaffSweep",
		"GAManifestWeaponTalismanRake",
	},
	modList = {
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- minion_does_not_equip_quiver [minion_does_not_equip_quiver = 1]
		-- monster_gets_item_stats [monster_gets_item_stats = 1]
		-- untargetable_by_monster_ai [untargetable_by_monster_ai = 1]
		mod("DamageTaken", "MORE", -100, 0, 0), -- set_base_cannot_be_damaged [set_base_cannot_be_damaged = 1]
		-- set_cannot_be_chained_from [set_cannot_be_chained_from = 1]
		mod("Life", "OVERRIDE", 1, 0, 0), -- set_base_maximum_life_is_one [set_base_maximum_life_is_one = 1]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		-- set_cannot_be_splashed_from [set_cannot_be_splashed_from = 1]
		-- immune_to_auras_from_other_teams [immune_to_auras_from_other_teams = 1]
		-- hide_buff_visuals [hide_buff_visuals = 1]
		-- base_hide_mini_life_bar [base_hide_mini_life_bar = 1]
		-- set_use_melee_pattern_range [set_use_melee_pattern_range = 0]
	},
}

minions["RavenousSwarm"] = {
	name = "Ravenous Swarm",
	monsterTags = { "beast", "slow_movement", "Unarmed_onhit_audio", },
	life = 0.7,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.84,
	damageSpread = 0.3,
	attackTime = 1,
	attackRange = 1,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 24,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"RavenousSwarmAttack",
	},
	modList = {
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["LivingLightning"] = {
	name = "Living Lightning",
	monsterTags = { "construct", "extra_small_height", "ghost_armour", "is_unarmed", "melee", "physical_affinity", "very_fast_movement", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.35,
	damageSpread = 0.8,
	attackTime = 1,
	attackRange = 20,
	accuracy = 1,
	critChance = 5,
	limit = "ActiveLivingLightningLimit",
	baseMovementSpeed = 97,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Construct",
	spawnLocation = {
	},
	skillList = {
		"LivingLightningZap",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		mod("CurseImmune", "FLAG", 1, 0, 0), -- immune_to_curses [immune_to_curses = 1]
		-- immune_to_auras_from_other_teams [immune_to_auras_from_other_teams = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_monster_no_drops_or_experience [set_monster_no_drops_or_experience = 1]
		-- set_monster_do_not_fracture [set_monster_do_not_fracture = 1]
		mod("FrenzyChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_frenzy_charges [set_max_frenzy_charges = 0]
		mod("EnduranceChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_endurance_charges [set_max_endurance_charges = 0]
		mod("PowerChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_power_charges [set_max_power_charges = 0]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		-- set_phase_through_objects [set_phase_through_objects = 1]
		-- untargetable_by_monster_ai [untargetable_by_monster_ai = 1]
		-- set_minion_cannot_be_directed [set_minion_cannot_be_directed = 1]
		mod("DamageTaken", "MORE", -100, 0, 0), -- set_base_cannot_be_damaged [set_base_cannot_be_damaged = 1]
		-- set_cannot_be_chained_from [set_cannot_be_chained_from = 1]
		mod("Life", "OVERRIDE", 1, 0, 0), -- set_base_maximum_life_is_one [set_base_maximum_life_is_one = 1]
		-- set_cannot_be_splashed_from [set_cannot_be_splashed_from = 1]
		-- hide_buff_visuals [hide_buff_visuals = 1]
		-- base_hide_mini_life_bar [base_hide_mini_life_bar = 1]
	},
}

minions["TacticianMinion"] = {
	name = "Artillery Squad",
	monsterTags = { "ranged", "Unarmed_onhit_audio", "very_slow_movement", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.67,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 6,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 8,
	spectreReservation = 50,
	companionReservation = 30,
	spawnLocation = {
	},
	skillList = {
		"DeathFromAboveDaemonMinion",
	},
	modList = {
		mod("CurseImmune", "FLAG", 1, 0, 0), -- immune_to_curses [immune_to_curses = 1]
		-- immune_to_auras_from_other_entities [immune_to_auras_from_other_entities = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- mana_regeneration_rate_per_minute_% [mana_regeneration_rate_per_minute_% = 100]
		-- base_maximum_mana [base_maximum_mana = 100000]
		-- set_monster_no_drops_or_experience [set_monster_no_drops_or_experience = 1]
		-- set_monster_do_not_fracture [set_monster_do_not_fracture = 1]
		mod("FrenzyChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_frenzy_charges [set_max_frenzy_charges = 0]
		mod("EnduranceChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_endurance_charges [set_max_endurance_charges = 0]
		mod("PowerChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_power_charges [set_max_power_charges = 0]
		mod("HiddenMonster", "FLAG", 1, 0, 0), -- is_hidden_monster [is_hidden_monster = 1]
		mod("Condition:CannotBeDamaged", "FLAG", 1, 0, 0), -- base_cannot_be_damaged [base_cannot_be_damaged = 1]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		-- is_daemon [is_daemon = 1]
		-- set_skill_can_be_active_blocked_from_all_directions [set_skill_can_be_active_blocked_from_all_directions = 1]
	},
}

minions["HyenaMinion"] = {
	name = "Cackling Companion",
	monsterTags = { "beast", "Beast_onhit_audio", "mammal_beast", "melee", "not_int", "not_str", "physical_affinity", "red_blood", "very_fast_movement", },
	life = 1.1,
	baseDamageIgnoresAttackSpeed = true,
	evasion = 0.3,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.77,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 9,
	accuracy = 1,
	critChance = 8,
	limit = "HyenaLimit",
	baseMovementSpeed = 50,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"HyenaCompanionMelee",
		"HyenaHinderWhoopMinion",
		"HyenaStandaloneWhoop",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["WolfMinion"] = {
	name = "Wolf Companion",
	monsterTags = { "beast", "fast_movement", "mammal_beast", "not_int", "not_str", "Snap_onhit_audio", },
	life = 1.1,
	baseDamageIgnoresAttackSpeed = true,
	evasion = 0.3,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.7,
	damageSpread = 0.2,
	attackTime = 0.8,
	attackRange = 12,
	accuracy = 1,
	critChance = 5,
	limit = "WolfLimit",
	baseMovementSpeed = 42,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"MeleeAtAnimationSpeedWolfCompanion",
		"WolfLeapAttackMinion",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
	},
}

minions["BeetleMinion"] = {
	name = "Corpse Beetle",
	monsterTags = { "allows_inc_aoe", "beast", "Claw_onhit_audio", "insect", "sand_blood", "very_fast_movement", },
	life = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 6,
	accuracy = 1,
	critChance = 5,
	limit = "BeetleLimit",
	baseMovementSpeed = 90,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"CorpseBeetleExplode",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		mod("CurseImmune", "FLAG", 1, 0, 0), -- immune_to_curses [immune_to_curses = 1]
		-- immune_to_auras_from_other_entities [immune_to_auras_from_other_entities = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_monster_no_drops_or_experience [set_monster_no_drops_or_experience = 1]
		-- set_monster_do_not_fracture [set_monster_do_not_fracture = 1]
		mod("FrenzyChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_frenzy_charges [set_max_frenzy_charges = 0]
		mod("EnduranceChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_endurance_charges [set_max_endurance_charges = 0]
		mod("PowerChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_power_charges [set_max_power_charges = 0]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		-- set_phase_through_objects [set_phase_through_objects = 1]
		-- untargetable_by_monster_ai [untargetable_by_monster_ai = 1]
	},
}

minions["WaterDjinn"] = {
	name = "Navira, the Last Mirage",
	monsterTags = { "humanoid", "medium_movement", "Unarmed_onhit_audio", "water", "water_elemental", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 0,
	attackRange = 6,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 35,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Humanoid",
	spawnLocation = {
	},
	skillList = {
		"WaterBubbleWaterDjinn",
		"ChilledGroundBurstWaterDjinn",
		"ESRechargeForceRestartWaterDjinn",
		"ChilledGroundOasisConvertWaterDjinn",
		"PassiveTriggeredManaWaveWaterDjinn",
	},
	modList = {
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- no_blood_on_death [no_blood_on_death = 1]
		-- set_cannot_be_chained_from [set_cannot_be_chained_from = 1]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		-- set_cannot_be_splashed_from [set_cannot_be_splashed_from = 1]
		-- immune_to_auras_from_other_teams [immune_to_auras_from_other_teams = 1]
		-- hide_buff_visuals [hide_buff_visuals = 1]
		-- untargetable_by_monster_ai [untargetable_by_monster_ai = 1]
		-- set_cannot_die [set_cannot_die = 1]
		mod("StunDuration", "OVERRIDE", 5.6, 0, 0), -- set_base_heavy_stun_duration_ms [set_base_heavy_stun_duration_ms = 5600]
		-- set_minion_cannot_be_directed [set_minion_cannot_be_directed = 1]
		-- set_projectiles_do_not_collide_with_you [set_projectiles_do_not_collide_with_you = 1]
	},
}

minions["FireDjinn"] = {
	name = "Ruzhan, the Blazing Sword",
	monsterTags = { "elemental", "fire", "humanoid", "medium_movement", "Unarmed_onhit_audio", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1.4,
	damageSpread = 0.2,
	attackTime = 0,
	attackRange = 6,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 35,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Humanoid",
	spawnLocation = {
	},
	skillList = {
		"LivingBombFireDjinn",
		"FireRuneFireDjinn",
		"MeteorFireDjinn",
		"MassFusilladeFireDjinn",
		"FlameSliceFireDjinn",
	},
	modList = {
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- no_blood_on_death [no_blood_on_death = 1]
		-- set_cannot_be_chained_from [set_cannot_be_chained_from = 1]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		-- set_cannot_be_splashed_from [set_cannot_be_splashed_from = 1]
		-- immune_to_auras_from_other_teams [immune_to_auras_from_other_teams = 1]
		-- hide_buff_visuals [hide_buff_visuals = 1]
		-- untargetable_by_monster_ai [untargetable_by_monster_ai = 1]
		-- set_cannot_die [set_cannot_die = 1]
		mod("StunDuration", "OVERRIDE", 5.6, 0, 0), -- set_base_heavy_stun_duration_ms [set_base_heavy_stun_duration_ms = 5600]
		-- set_minion_cannot_be_directed [set_minion_cannot_be_directed = 1]
		-- set_projectiles_do_not_collide_with_you [set_projectiles_do_not_collide_with_you = 1]
	},
}

minions["SandDjinn"] = {
	name = "Kelari, the Tainted Sands",
	monsterTags = { "earth_elemental", "humanoid", "medium_movement", "sand_blood", "Unarmed_onhit_audio", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 0,
	attackRange = 6,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 35,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Humanoid",
	spawnLocation = {
	},
	skillList = {
		"KnifeThrowSandDjinn",
		"ExplosiveTeleportSandDjinn",
		"HandSlamSandDjinn",
	},
	modList = {
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- no_blood_on_death [no_blood_on_death = 1]
		-- set_cannot_be_chained_from [set_cannot_be_chained_from = 1]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		-- set_cannot_be_splashed_from [set_cannot_be_splashed_from = 1]
		-- immune_to_auras_from_other_teams [immune_to_auras_from_other_teams = 1]
		-- hide_buff_visuals [hide_buff_visuals = 1]
		-- untargetable_by_monster_ai [untargetable_by_monster_ai = 1]
		-- set_cannot_die [set_cannot_die = 1]
		mod("StunDuration", "OVERRIDE", 5.6, 0, 0), -- set_base_heavy_stun_duration_ms [set_base_heavy_stun_duration_ms = 5600]
		-- set_minion_cannot_be_directed [set_minion_cannot_be_directed = 1]
		-- set_projectiles_do_not_collide_with_you [set_projectiles_do_not_collide_with_you = 1]
	},
}

minions["MistRaven"] = {
	name = "Raven Conspiracy",
	monsterTags = { "ranged", "Unarmed_onhit_audio", "very_slow_movement", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.67,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 6,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 8,
	spectreReservation = 50,
	companionReservation = 30,
	spawnLocation = {
	},
	skillList = {
		"ApplyTangmazuSwarmAuraPlayer",
		"TangmazuMadFlightMinion",
	},
	modList = {
		mod("CurseImmune", "FLAG", 1, 0, 0), -- immune_to_curses [immune_to_curses = 1]
		-- immune_to_auras_from_other_entities [immune_to_auras_from_other_entities = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- mana_regeneration_rate_per_minute_% [mana_regeneration_rate_per_minute_% = 100]
		-- base_maximum_mana [base_maximum_mana = 100000]
		-- set_monster_no_drops_or_experience [set_monster_no_drops_or_experience = 1]
		-- set_monster_do_not_fracture [set_monster_do_not_fracture = 1]
		mod("FrenzyChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_frenzy_charges [set_max_frenzy_charges = 0]
		mod("EnduranceChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_endurance_charges [set_max_endurance_charges = 0]
		mod("PowerChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_power_charges [set_max_power_charges = 0]
		mod("HiddenMonster", "FLAG", 1, 0, 0), -- is_hidden_monster [is_hidden_monster = 1]
		mod("Condition:CannotBeDamaged", "FLAG", 1, 0, 0), -- base_cannot_be_damaged [base_cannot_be_damaged = 1]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		-- is_daemon [is_daemon = 1]
		-- set_skill_can_be_active_blocked_from_all_directions [set_skill_can_be_active_blocked_from_all_directions = 1]
	},
}

minions["AzmerianSwarm"] = {
	name = "[DNT] Azmerian Wisp Swarm",
	monsterTags = { "beast", "Unarmed_onhit_audio", "very_fast_movement", },
	life = 0.7,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 0.84,
	damageSpread = 0.3,
	attackTime = 1,
	attackRange = 1,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "None",
	weaponType2 = "None",
	limit = "AzmerianSwarmLimit",
	baseMovementSpeed = 60,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"AzmerianSwarmAttack",
	},
	modList = {
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		mod("CurseImmune", "FLAG", 1, 0, 0), -- immune_to_curses [immune_to_curses = 1]
		-- immune_to_auras_from_other_entities [immune_to_auras_from_other_entities = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- mana_regeneration_rate_per_minute_% [mana_regeneration_rate_per_minute_% = 100]
		-- base_maximum_mana [base_maximum_mana = 100000]
		-- set_monster_no_drops_or_experience [set_monster_no_drops_or_experience = 1]
		-- set_monster_do_not_fracture [set_monster_do_not_fracture = 1]
		mod("FrenzyChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_frenzy_charges [set_max_frenzy_charges = 0]
		mod("EnduranceChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_endurance_charges [set_max_endurance_charges = 0]
		mod("PowerChargesMax", "OVERRIDE", 0, 0, 0), -- set_max_power_charges [set_max_power_charges = 0]
		mod("HiddenMonster", "FLAG", 1, 0, 0), -- is_hidden_monster [is_hidden_monster = 1]
		mod("Condition:CannotBeDamaged", "FLAG", 1, 0, 0), -- base_cannot_be_damaged [base_cannot_be_damaged = 1]
		mod("StunImmune", "FLAG", 1, 0, 0), -- base_cannot_be_stunned [base_cannot_be_stunned = 1]
		mod("KnockbackImmune", "FLAG", 1, 0, 0), -- cannot_be_knocked_back [cannot_be_knocked_back = 1]
		mod("FreezeImmune", "FLAG", 1, 0, 0), -- base_cannot_be_frozen [base_cannot_be_frozen = 1]
		mod("Life", "OVERRIDE", 1, 0, 0), -- base_maximum_life_is_one [base_maximum_life_is_one = 1]
	},
}

minions["AzmerianWolf"] = {
	name = "Azmerian Wolf",
	monsterTags = { "1HSword_onhit_audio", "beast", "mammal_beast", "medium_movement", "not_int", "not_str", "red_blood", },
	life = 2.7,
	baseDamageIgnoresAttackSpeed = true,
	evasion = 0.3,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 2.43,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 18,
	accuracy = 1,
	critChance = 5,
	weaponType1 = "None",
	weaponType2 = "None",
	baseMovementSpeed = 36,
	spectreReservation = 105,
	companionReservation = 49.2,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"MeleeAtAnimationSpeedWolfPackleader",
		"WolfPackleaderDashAttack",
		"WolfPackleaderLungeBite",
		"GTPackleaderGreatHuntDash",
		"TBPackleaderGreatHuntDash",
		"GAPackleaderGreatHuntDash",
		"GreatHuntPackleaderMinion",
		"EGPackleaderPrimalInspiration",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		mod("StunDuration", "OVERRIDE", 2, 0, 0), -- set_base_heavy_stun_duration_ms [set_base_heavy_stun_duration_ms = 2000]
		-- has_quadruped_head_control_while_turning [has_quadruped_head_control_while_turning = 1]
		-- quadruped_head_turn_duration_ms [quadruped_head_turn_duration_ms = 200]
	},
}

minions["BearCompanion"] = {
	name = "Wild Bear Spirit",
	monsterTags = { "beast", "Claw_onhit_audio", "mammal_beast", "medium_movement", "not_dex", "not_int", "red_blood", },
	life = 1.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 4.5,
	damageSpread = 0.2,
	attackTime = 0.8,
	attackRange = 20,
	accuracy = 1,
	critChance = 5,
	baseMovementSpeed = 37,
	spectreReservation = 67,
	companionReservation = 36.6,
	monsterCategory = "Beast",
	spawnLocation = {
	},
	skillList = {
		"CompanionBearMaul",
		"CompanionBearSlam",
		"CompanionBearWarcry",
		"CompanionBearLeap",
		"CompanionBearLeapImpact",
		"CompanionBearLeapImpact2",
	},
	modList = {
		-- MonsterNoDropsOrExperience [monster_no_drops_or_experience = 1]
		-- MonsterIgnoreActorScaleFromStats [ignore_actor_scale_from_stats = 1]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- is_bear_companion [is_bear_companion = 1]
		-- no_blood_on_death [no_blood_on_death = 1]
		-- override_turn_duration_ms [override_turn_duration_ms = 600]
		-- has_quadruped_head_control_while_turning [has_quadruped_head_control_while_turning = 1]
		-- quadruped_head_turn_duration_ms [quadruped_head_turn_duration_ms = 200]
		-- base_presence_radius [base_presence_radius = 80]
		mod("DamageTaken", "INC", -50, 0, 0), -- set_base_damage_taken_+% [set_base_damage_taken_+% = -50]
	},
}

minions["Wardbound"] = {
	name = "Wardbound Caster",
	monsterTags = { "fast_movement", "humanoid", "not_str", "red_blood", "Unarmed_onhit_audio", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.15,
	evasion = 0.25,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	companionFireResist = 0,
	companionColdResist = 0,
	companionLightningResist = 0,
	companionChaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 14,
	accuracy = 1,
	critChance = 5,
	limit = "WardboundLimit",
	baseMovementSpeed = 41,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Humanoid",
	spawnLocation = {
	},
	skillList = {
		"GSWardboundMinionBlast",
	},
	modList = {
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_action_attack_or_cast_time_uses_animation_length [set_action_attack_or_cast_time_uses_animation_length = 0]
		-- set_item_drop_slots [set_item_drop_slots = 0]
		-- set_monster_no_drops_or_experience [set_monster_no_drops_or_experience = 1]
		-- set_monster_do_not_fracture [set_monster_do_not_fracture = 1]
		-- set_minion_cannot_be_directed [set_minion_cannot_be_directed = 1]
	},
}
