-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="{0} second delay between Visages"
			}
		},
		stats={
			[1]="base_cooldown_modifiable_repeat_interval_ms"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Modifiers to Cooldown Recovery Rate also apply to\nVisage appearance frequency"
			}
		},
		stats={
			[1]="cooldown_recovery_modifiers_also_apply_to_repeat_interval"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="{0}% more Visage frequency per Spell Visages could cast"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				text="{0}% less Visage frequency per Spell Visages could cast"
			}
		},
		stats={
			[1]="spellflux_frequency_+%_final_per_socketed_valid_spell"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Casting the matching Spell before the next\nVisage appears Empowers that Spell\nEmpowered Spells deal {0}% more damage"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				text="Casting the matching Spell before the next\nVisage appears Empowers that Spell\nEmpowered Spells deal {0}% less damage"
			}
		},
		stats={
			[1]="spellflux_spell_damage_+%_final_if_matching_flux_cast"
		}
	},
	["base_cooldown_modifiable_repeat_interval_ms"]=1,
	["cooldown_recovery_modifiers_also_apply_to_repeat_interval"]=2,
	parent="skill_stat_descriptions",
	["spellflux_frequency_+%_final_per_socketed_valid_spell"]=3,
	["spellflux_spell_damage_+%_final_if_matching_flux_cast"]=4
}