-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				text="Damage radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Damage radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="{0}% more Area of Effect per Raven"
			}
		},
		stats={
			[1]="flock_area_of_effect_+%_final_per_tangmazu_raven_in_owners_flock"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="{0}% more Damage over time per Raven"
			}
		},
		stats={
			[1]="flock_damage_over_time_+%_final_per_tangmazu_raven_in_owners_flock"
		}
	},
	["active_skill_area_of_effect_radius"]=1,
	["active_skill_base_area_of_effect_radius"]=2,
	["flock_area_of_effect_+%_final_per_tangmazu_raven_in_owners_flock"]=3,
	["flock_damage_over_time_+%_final_per_tangmazu_raven_in_owners_flock"]=4,
	parent="skill_stat_descriptions"
}