-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				text="Fire-Infused explosion radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Fire-Infused explosion radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_secondary_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				text="Creates Ignited Ground every {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Creates Ignited Ground every {0} seconds"
			}
		},
		stats={
			[1]="ball_lightning_infused_burning_ground_interval_ms"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				text="Fire-Infused explosion deals {0} to {1} Fire damage"
			}
		},
		stats={
			[1]="spell_minimum_base_fire_damage",
			[2]="spell_maximum_base_fire_damage"
		}
	},
	["active_skill_base_secondary_area_of_effect_radius"]=1,
	["ball_lightning_infused_burning_ground_interval_ms"]=2,
	parent="skill_stat_descriptions",
	["spell_maximum_base_fire_damage"]=3,
	["spell_minimum_base_fire_damage"]=3
}