-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="When Hit by an enemy, gain Armour equal to {0}% of\nEnergy Shield lost"
			}
		},
		stats={
			[1]="barkskin_armour_to_gain_as_%_of_energy_shield_lost_to_enemy_hits"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				text="Buff duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Buff duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[3]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	["barkskin_armour_to_gain_as_%_of_energy_shield_lost_to_enemy_hits"]=1,
	["base_skill_effect_duration"]=2,
	parent="skill_stat_descriptions",
	["skill_effect_duration"]=3
}