-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="spell_cast_time_cannot_be_modified"
		}
	},
	[2]={
		stats={
			[1]="dodge_roll_base_travel_distance"
		}
	},
	["dodge_roll_base_travel_distance"]=2,
	parent="skill_stat_descriptions",
	["spell_cast_time_cannot_be_modified"]=1
}