-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="generic_ongoing_trigger_maximum_energy"
		}
	},
	[2]={
		stats={
			[1]="generic_ongoing_trigger_triggers_at_maximum_energy"
		}
	},
	[3]={
		stats={
			[1]="display_generic_ongoing_trigger_hide_energy_stats"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Can only socket Lightning Spells\nTriggers all Socketed Spells and loses all Energy on reaching maximum Energy"
			}
		},
		stats={
			[1]="generic_ongoing_trigger_triggers_at_maximum_energy"
		}
	},
	["display_generic_ongoing_trigger_hide_energy_stats"]=3,
	["generic_ongoing_trigger_maximum_energy"]=1,
	["generic_ongoing_trigger_triggers_at_maximum_energy"]=4,
	parent="skill_stat_descriptions"
}