-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[2]={
		stats={
			[1]="non_skill_base_all_damage_%_to_gain_as_lightning_with_spells_from_buff"
		}
	},
	[3]={
		stats={
			[1]="display_this_skill_cooldown_does_not_recover_during_buff"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="{0}% of Mana and Life spent while in the storm is\nadded to this Skill's Mana Cost per Second"
			}
		},
		stats={
			[1]="mana_tempest_mana_cost_%_to_add_to_cost_per_second"
		}
	},
	["active_skill_base_area_of_effect_radius"]=1,
	["display_this_skill_cooldown_does_not_recover_during_buff"]=3,
	["mana_tempest_mana_cost_%_to_add_to_cost_per_second"]=4,
	["non_skill_base_all_damage_%_to_gain_as_lightning_with_spells_from_buff"]=2,
	parent="skill_stat_descriptions"
}