-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="non_skill_base_all_damage_%_to_gain_as_lightning_with_spells_from_buff"
		}
	},
	[2]={
		stats={
			[1]="non_skill_base_all_damage_%_to_gain_as_cold_with_spells_from_buff"
		}
	},
	[3]={
		stats={
			[1]="spell_minimum_base_cold_damage"
		}
	},
	[4]={
		stats={
			[1]="spell_maximum_base_cold_damage"
		}
	},
	[5]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="Chilled Ground radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="Chilled Ground radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_tertiary_area_of_effect_radius"
		}
	},
	["active_skill_base_tertiary_area_of_effect_radius"]=5,
	["non_skill_base_all_damage_%_to_gain_as_cold_with_spells_from_buff"]=2,
	["non_skill_base_all_damage_%_to_gain_as_lightning_with_spells_from_buff"]=1,
	parent="skill_stat_descriptions",
	["spell_maximum_base_cold_damage"]=4,
	["spell_minimum_base_cold_damage"]=3
}