-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Culling Strike"
			}
		},
		stats={
			[1]="spells_have_culling_strike"
		}
	},
	parent="skill_stat_descriptions",
	["spells_have_culling_strike"]=1
}