-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="total_number_of_projectiles_to_fire_from_stats"
		}
	},
	parent="skill_stat_descriptions",
	["total_number_of_projectiles_to_fire_from_stats"]=1
}