-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Regenerate {0} Rage per second"
			}
		},
		stats={
			[1]="ceaseless_rage_base_rage_regeneration_per_minute"
		}
	},
	["ceaseless_rage_base_rage_regeneration_per_minute"]=1,
	parent="skill_stat_descriptions"
}