-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Grants each of Hindsight, Foresight, and\nSight Beyond Sight, in sequence\nHindsight lasts for a {0} second duration"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="{0:+d} seconds to Beyond Sight duration"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Foresight prevents Dodge Roll from Avoiding Hits and lasts until immediately before you are Hit while Dodge Rolling\nSight Beyond Sight makes you unable to die and lasts for a {0} second duration\nFully recover Life when you gain Sight Beyond Sight"
			}
		},
		stats={
			[1]="base_secondary_skill_effect_duration"
		}
	},
	[3]={
		[1]={
		},
		stats={
			[1]="secondary_skill_effect_duration"
		}
	},
	[4]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	["base_secondary_skill_effect_duration"]=2,
	["base_skill_effect_duration"]=1,
	parent="skill_stat_descriptions",
	["secondary_skill_effect_duration"]=3,
	["skill_effect_duration"]=4
}