-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				text="DNT Spore Cloud duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT Spore Cloud duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="DNT Spore Cloud deals {0} Chaos damage per second"
			}
		},
		stats={
			[1]="fungal_terrain_spore_cloud_chaos_damage_per_minute"
		}
	},
	["base_skill_effect_duration"]=1,
	["fungal_terrain_spore_cloud_chaos_damage_per_minute"]=2,
	parent="skill_stat_descriptions"
}