-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				text="DNT Mushroom duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT Mushroom duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT Maximum {0} Mushrooms"
			}
		},
		stats={
			[1]="fungal_terrain_maximum_mushrooms"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT Spawns {0} Mushrooms per Skill Use"
			}
		},
		stats={
			[1]="fungal_terrain_number_of_mushrooms_per_use"
		}
	},
	["base_skill_effect_duration"]=1,
	["fungal_terrain_maximum_mushrooms"]=2,
	["fungal_terrain_number_of_mushrooms_per_use"]=3,
	parent="skill_stat_descriptions"
}