-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Remnants store {0}% of Minion maximum Life"
			}
		},
		stats={
			[1]="grim_remnant_health_stored_in_globe_%"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="You can store up to {0} collected Minion Life"
			}
		},
		stats={
			[1]="grim_remnant_max_health_stored"
		}
	},
	["grim_remnant_health_stored_in_globe_%"]=1,
	["grim_remnant_max_health_stored"]=2,
	parent="skill_stat_descriptions"
}