-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Images can be created within {0} metre radius of you"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=100,
						[2]=100
					}
				},
				text="Creating an Image spends Socketed Skill's Cost"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Creating an Image spends {0}% of Socketed Skill's Cost"
			}
		},
		stats={
			[1]="mantra_of_illusions_cloned_skill_mana_cost_%"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="Consumes a Power Charge to create {0} additional Image"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="Consumes a Power Charge to create {0} additional Images"
			}
		},
		stats={
			[1]="mantra_of_illusions_bonus_illusions_when_consuming_power_charge"
		}
	},
	["active_skill_area_of_effect_radius"]=1,
	["active_skill_base_area_of_effect_radius"]=2,
	["mantra_of_illusions_bonus_illusions_when_consuming_power_charge"]=4,
	["mantra_of_illusions_cloned_skill_mana_cost_%"]=3,
	parent="skill_stat_descriptions"
}