-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				text="Flames of Chayula fade after {0} second if not picked up"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Flames of Chayula fade after {0} seconds if not picked up"
			}
		},
		stats={
			[1]="base_remnant_duration_ms"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Flame of Chayula within 5m of you are revealed"
			}
		},
		stats={
			[1]="breach_flame_spawn_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Flames of Chayula have {0}% increased effect"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				text="Flames of Chayula have {0}% reduced effect"
			}
		},
		stats={
			[1]="remnant_effect_+%"
		}
	},
	[4]={
		[1]={
		},
		stats={
			[1]="virtual_remnant_duration_ms"
		}
	},
	["base_remnant_duration_ms"]=1,
	["breach_flame_spawn_radius"]=2,
	parent="skill_stat_descriptions",
	["remnant_effect_+%"]=3,
	["virtual_remnant_duration_ms"]=4
}