-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Aura grants {0:+d}% to Lightning Resistance"
			}
		},
		stats={
			[1]="base_skill_buff_lightning_damage_resistance_%_to_apply"
		}
	},
	[2]={
		[1]={
		},
		stats={
			[1]="skill_aura_buff_lightning_damage_resistance_%_magnitude_to_apply"
		}
	},
	["base_skill_buff_lightning_damage_resistance_%_to_apply"]=1,
	parent="skill_stat_descriptions",
	["skill_aura_buff_lightning_damage_resistance_%_magnitude_to_apply"]=2
}