-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="divide_by_one_hundred_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="DNT-UNUSED Gains {0} Energy per ten Mana spent on ranged Attacks"
			}
		},
		stats={
			[1]="arcane_archery_gain_X_centienergy_per_10_mana_cost_of_ranged_attack"
		}
	},
	["arcane_archery_gain_X_centienergy_per_10_mana_cost_of_ranged_attack"]=1,
	parent="skill_stat_descriptions"
}