-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="You cannot gain Arctic Petals from this Skill's Critical Hits"
			}
		},
		stats={
			[1]="base_skill_cannot_generate_midnight_star_petals"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="+1 Arctic Petal per Power of targets Killed with Critical Hits"
			}
		},
		stats={
			[1]="midnight_star_gain_ice_seeds_equal_to_enemy_power_on_kill_with_critical_hit"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="{0:+d} Arctic Petal on Critically Hitting Rare or Unique targets"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="{0:+d} Arctic Petals on Critically Hitting Rare or Unique targets"
			}
		},
		stats={
			[1]="midnight_star_gain_x_ice_seeds_when_you_critically_hit_a_rare_or_unique_enemy"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				text="Consumes {0} Arctic Petals to create {1} Ice Crystals when able"
			}
		},
		stats={
			[1]="midnight_star_attempt_to_consume_x_ice_seeds_to_create_an_ice_crystal_each_time_you_gain_ice_seeds",
			[2]="unique_nattblom_crystals_per_trigger"
		}
	},
	["base_skill_cannot_generate_midnight_star_petals"]=1,
	["midnight_star_attempt_to_consume_x_ice_seeds_to_create_an_ice_crystal_each_time_you_gain_ice_seeds"]=4,
	["midnight_star_gain_ice_seeds_equal_to_enemy_power_on_kill_with_critical_hit"]=2,
	["midnight_star_gain_x_ice_seeds_when_you_critically_hit_a_rare_or_unique_enemy"]=3,
	parent="skill_stat_descriptions",
	["unique_nattblom_crystals_per_trigger"]=4
}