-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
		},
		stats={
			[1]="active_skill_buff_stack_gain_frequency_ms"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				text="Gains a Stage every second, up to a maximum of {1} Stages"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				text="Gains a Stage every {0} seconds, up to a maximum of {1} Stages"
			}
		},
		stats={
			[1]="base_active_skill_buff_stack_gain_frequency_ms",
			[2]="maximum_number_of_arctic_armour_stationary_stacks"
		}
	},
	[3]={
		[1]={
		},
		stats={
			[1]="virtual_maximum_number_of_arctic_armour_stationary_stacks"
		}
	},
	["active_skill_buff_stack_gain_frequency_ms"]=1,
	["base_active_skill_buff_stack_gain_frequency_ms"]=2,
	["maximum_number_of_arctic_armour_stationary_stacks"]=2,
	parent="skill_stat_descriptions",
	["virtual_maximum_number_of_arctic_armour_stationary_stacks"]=3
}