-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Each enemy can have up to 1 Pustule attached"
			}
		},
		stats={
			[1]="skill_specific_stat_description_mode"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]=1,
						[2]="#"
					}
				},
				text="Stored Poison grants up to {1}% more explosion Damage"
			}
		},
		stats={
			[1]="toxic_pustule_burst_1%_more_damage_per_x_stored_poison",
			[2]="toxic_pustule_max_burst_damage_+%_final_from_stored_poison"
		}
	},
	["active_skill_base_area_of_effect_radius"]=1,
	parent="skill_stat_descriptions",
	["skill_specific_stat_description_mode"]=2,
	["toxic_pustule_burst_1%_more_damage_per_x_stored_poison"]=3,
	["toxic_pustule_max_burst_damage_+%_final_from_stored_poison"]=3
}