-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="base_secondary_skill_effect_duration"
		}
	},
	[2]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				text="Explosion radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Explosion radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="{0}% more Stun buildup on Hit\nper Fragility on the target"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]=1
					}
				},
				text="{0}% less Stun buildup on Hit\nper Fragility on the target"
			}
		},
		stats={
			[1]="curse_repulsion_shockwave_hit_damage_stun_multiplier_+%_final_per_fragility_on_special_object"
		}
	},
	["active_skill_area_of_effect_radius"]=2,
	["active_skill_base_area_of_effect_radius"]=3,
	["base_secondary_skill_effect_duration"]=1,
	["curse_repulsion_shockwave_hit_damage_stun_multiplier_+%_final_per_fragility_on_special_object"]=4,
	parent="skill_stat_descriptions"
}