-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="never_freeze"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Triggers Ice Fragments on Hit against\nFrozen enemies, no more than once per use"
			}
		},
		stats={
			[1]="frozen_claws_hits_trigger_ballistic_ice_chunks_vs_frozen_enemies"
		}
	},
	["frozen_claws_hits_trigger_ballistic_ice_chunks_vs_frozen_enemies"]=2,
	["never_freeze"]=1,
	parent="skill_stat_descriptions"
}