-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Generates {0}% of Runic Ward spent as Glory for this Skill"
			}
		},
		stats={
			[1]="active_skill_generates_%_of_ward_spent_as_glory"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="Creates {0} Temporary Minion"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="Creates {0} Temporary Minions"
			}
		},
		stats={
			[1]="verisium_comet_number_of_minions_to_create"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="Limit {0} Temporary Minion"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="Limit {0} Temporary Minions"
			}
		},
		stats={
			[1]="base_number_of_verisium_octopus_minions_allowed"
		}
	},
	[4]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[5]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				text="Impact radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Impact radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	["active_skill_area_of_effect_radius"]=4,
	["active_skill_base_area_of_effect_radius"]=5,
	["active_skill_generates_%_of_ward_spent_as_glory"]=1,
	["base_number_of_verisium_octopus_minions_allowed"]=3,
	parent="skill_stat_descriptions",
	["verisium_comet_number_of_minions_to_create"]=2
}