-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="active_skill_generates_mp_%_glory_per_heavy_stun"
		}
	},
	[2]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				text="Ignited Ground radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Ignited Ground radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Gains Radius over the Ground Spear's lifetime, up to {0}% more at the end of the Spear's lifetime"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				text="Loses Radius over the Ground Spear's lifetime, up to {0}% less at the end of the Spear's lifetime"
			}
		},
		stats={
			[1]="solaris_spear_ground_expands_to_+%_final_by_skill_end"
		}
	},
	["active_skill_area_of_effect_radius"]=2,
	["active_skill_base_area_of_effect_radius"]=3,
	["active_skill_generates_mp_%_glory_per_heavy_stun"]=1,
	parent="skill_stat_descriptions",
	["solaris_spear_ground_expands_to_+%_final_by_skill_end"]=4
}