-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[2]={
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="This Minion uses your Culling Strike threshold"
			}
		},
		stats={
			[1]="use_owners_culling_threshold_instead_of_your_own"
		}
	},
	["active_skill_area_of_effect_radius"]=2,
	["active_skill_base_area_of_effect_radius"]=1,
	parent="skill_stat_descriptions",
	["use_owners_culling_threshold_instead_of_your_own"]=3
}