-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Triggers Navira's Calming when Commanded to use a\nSkill, granting nearby Allies increased Mana Regeneration"
			}
		},
		stats={
			[1]="skill_specific_stat_description_mode"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Triggers Navira's Calming when Commanded to\nuse a Skill, granting nearby Allies {0}% increased\nMana Regeneration for 4 seconds"
			}
		},
		stats={
			[1]="water_djinn_mana_wave_mana_regeneration_rate_+%"
		}
	},
	parent="skill_stat_descriptions",
	["skill_specific_stat_description_mode"]=1,
	["water_djinn_mana_wave_mana_regeneration_rate_+%"]=2
}