-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Raven Flock's Skills have {0}% increased Area of Effect"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				text="Raven Flock's Skills have {0}% reduced Area of Effect"
			}
		},
		stats={
			[1]="base_skill_area_of_effect_+%"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="divide_by_one_thousand",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				text="A Raven joins the Flock every {0} second while a Rare or Unique enemy is in your Presence"
			},
			[2]={
				[1]={
					k="divide_by_one_thousand",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="A Raven joins the Flock every {0} seconds while a Rare or Unique enemy is in your Presence"
			}
		},
		stats={
			[1]="tangmazu_raven_added_to_your_flock_every_x_msec_a_rare_or_unique_enemy_is_in_your_presence"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="A Raven joins the Flock for every {0} total Power of enemies slain by you or your Minions"
			}
		},
		stats={
			[1]="tangmazu_raven_added_to_your_flock_every_x_power_of_enemies_killed"
		}
	},
	[4]={
		[1]={
		},
		stats={
			[1]="tangmazu_raven_flock_count"
		}
	},
	["base_skill_area_of_effect_+%"]=1,
	parent="skill_stat_descriptions",
	["tangmazu_raven_added_to_your_flock_every_x_msec_a_rare_or_unique_enemy_is_in_your_presence"]=2,
	["tangmazu_raven_added_to_your_flock_every_x_power_of_enemies_killed"]=3,
	["tangmazu_raven_flock_count"]=4
}