-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT-UNUSED Cannot generate Edict Declaration"
			}
		},
		stats={
			[1]="cannot_generate_edict_declaration"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]=99
					}
				},
				text="DNT-UNUSED {0}% chance when hitting a Rare Monster with this attack to disable one of its Modifiers"
			},
			[2]={
				limit={
					[1]={
						[1]=100,
						[2]=100
					}
				},
				text="DNT-UNUSED Hitting a Rare Monster with this attack disable one of its Modifiers"
			}
		},
		stats={
			[1]="disable_rare_mod_on_hit_%_chance"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				text="DNT-UNUSED {0}% less Damage for each Second spent channelling"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="DNT-UNUSED {0}% more Damage for each Second spent channelling"
			}
		},
		stats={
			[1]="the_flawed_edict_damage_+%_final_to_add_each_second"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT-UNUSED {0}% of Life Spent while channelling is\nadded to this Skill's Life Cost per Second"
			}
		},
		stats={
			[1]="the_flawed_edict_life_cost_%_to_add_to_cost_per_second"
		}
	},
	[5]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT-UNUSED Requires Edict Declaration to be charged at 100% to use"
			}
		},
		stats={
			[1]="the_flawed_edict_required_declaration"
		}
	},
	["cannot_generate_edict_declaration"]=1,
	["disable_rare_mod_on_hit_%_chance"]=2,
	parent="skill_stat_descriptions",
	["the_flawed_edict_damage_+%_final_to_add_each_second"]=3,
	["the_flawed_edict_life_cost_%_to_add_to_cost_per_second"]=4,
	["the_flawed_edict_required_declaration"]=5
}