-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="{0} seconds between Blessings"
			}
		},
		stats={
			[1]="base_cooldown_modifiable_repeat_interval_ms"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Modifiers to Cooldown Recovery Rate also apply to\nBlessing frequency"
			}
		},
		stats={
			[1]="cooldown_recovery_modifiers_also_apply_to_repeat_interval"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Blessing recovers {0} Life and removes Curses and Elemental Ailments"
			}
		},
		stats={
			[1]="skill_time_of_need_gain_x_life"
		}
	},
	[4]={
		[1]={
		},
		stats={
			[1]="virtual_cooldown_modifiable_repeat_interval_ms"
		}
	},
	["base_cooldown_modifiable_repeat_interval_ms"]=1,
	["cooldown_recovery_modifiers_also_apply_to_repeat_interval"]=2,
	parent="skill_stat_descriptions",
	["skill_time_of_need_gain_x_life"]=3,
	["virtual_cooldown_modifiable_repeat_interval_ms"]=4
}