-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				text="Explosion applies Supported Curse for {0} second on Hit"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Explosion applies Supported Curse for {0} seconds on Hit"
			}
		},
		stats={
			[1]="curse_zone_explosion_apply_supported_curse_for_base_ms_on_hit"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Explosion radius is equal to that of the Cursed Ground"
			}
		},
		stats={
			[1]="display_skill_area_of_effect_radius_from_curse"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Explosion deals base Chaos Damage equal to {0}% of your Intelligence"
			}
		},
		stats={
			[1]="skill_base_chaos_damage_%_of_intelligence"
		}
	},
	["curse_zone_explosion_apply_supported_curse_for_base_ms_on_hit"]=1,
	["display_skill_area_of_effect_radius_from_curse"]=2,
	parent="skill_stat_descriptions",
	["skill_base_chaos_damage_%_of_intelligence"]=3
}