-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="never_ignite"
		}
	},
	[2]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				text="Pillar radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Pillar radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=100,
						[2]=100
					}
				},
				text="Grisly Pyres deal Damage equal to the highest expected remaining Damage of the Consumed Ignites"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Grisly Pyres deal Damage equal to {0}% of the highest expected remaining Damage of the Consumed Ignites"
			}
		},
		stats={
			[1]="unique_flame_pillar_fire_damage_equal_to_%_of_remaining_ignite_damage"
		}
	},
	["active_skill_area_of_effect_radius"]=2,
	["active_skill_base_area_of_effect_radius"]=3,
	["never_ignite"]=1,
	parent="skill_stat_descriptions",
	["unique_flame_pillar_fire_damage_equal_to_%_of_remaining_ignite_damage"]=4
}