-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="Creates {0} Skittering Stone"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="Creates {0} Skittering Stones"
			}
		},
		stats={
			[1]="support_hatching_elementals_number_of_elementals_per_hatch"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Level of Minions is based on Level of Triggering Skill"
			}
		},
		stats={
			[1]="display_minion_level_from_triggering_skill_level"
		}
	},
	[3]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				text="Minion duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Minion duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="Limit {0} Skittering Stone"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="Limit {0} Skittering Stones"
			}
		},
		stats={
			[1]="maximum_hatching_elementals_allowed"
		}
	},
	[5]={
		[1]={
		},
		stats={
			[1]="minion_duration"
		}
	},
	["base_skill_effect_duration"]=3,
	["display_minion_level_from_triggering_skill_level"]=2,
	["maximum_hatching_elementals_allowed"]=4,
	["minion_duration"]=5,
	parent="skill_stat_descriptions",
	["support_hatching_elementals_number_of_elementals_per_hatch"]=1
}