-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				text="Blast length is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Blast length is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="{0:+d}% Surpassing chance to grant a Power Charge on\nHeavy Stun, modified by Monster Power"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="{0}% Surpassing chance to grant a Power Charge on\nHeavy Stun, modified by Monster Power"
			}
		},
		stats={
			[1]="wing_blast_chance_to_gain_power_charge_on_stun_%"
		}
	},
	["active_skill_area_of_effect_radius"]=1,
	["active_skill_base_area_of_effect_radius"]=2,
	parent="skill_stat_descriptions",
	["wing_blast_chance_to_gain_power_charge_on_stun_%"]=3
}