-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Cannot inflict Shock"
			}
		},
		stats={
			[1]="never_shock"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Hits up to 8 enemies"
			}
		},
		stats={
			[1]="skill_specific_stat_description_mode"
		}
	},
	[3]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Additional Hits deal {0}% more damage"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Additional Hits deal {0}% less damage\nAdditional Hits convert 100% of Physical and\nElemental damage to Lightning"
			}
		},
		stats={
			[1]="skill_wrath_aura_shared_damage_+%_to_other_shocked_enemies_in_presence"
		}
	},
	["never_shock"]=1,
	parent="skill_stat_descriptions",
	["skill_specific_stat_description_mode"]=2,
	["skill_wrath_aura_shared_damage_+%_to_other_shocked_enemies_in_presence"]=3
}