-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				text="Immolation radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Immolation radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_secondary_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
		},
		stats={
			[1]="active_skill_secondary_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Empowered Flame Breath Gains {0}% of\ndamage as Lightning damage"
			}
		},
		stats={
			[1]="wyvern_devour_empowered_flame_breath_base_all_damage_%_to_gain_as_lightning"
		}
	},
	[4]={
		[1]={
			[1]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				text="Empowered Flame Breath costs {0}% less Rage per second"
			}
		},
		stats={
			[1]="wyvern_devour_empowered_flame_breath_rage_consumption_+%"
		}
	},
	["active_skill_base_secondary_area_of_effect_radius"]=1,
	["active_skill_secondary_area_of_effect_radius"]=2,
	parent="skill_stat_descriptions",
	["wyvern_devour_empowered_flame_breath_base_all_damage_%_to_gain_as_lightning"]=3,
	["wyvern_devour_empowered_flame_breath_rage_consumption_+%"]=4
}