// ============================================================

// tree-web.json data format (generated by scripts/gen_tree_data.py)
// Maps PoB2 TreeData/{version}/tree.json to a web-optimized version
// ============================================================



// ---- Basic Info ----
export interface TreeVersion {

  version: string        // e.g. "0_4"

  display: string        // e.g. "3.25"

  num: number

}



// ---- Constants ----
export interface TreeConstants {

  skillsPerOrbit: number[]     // [1, 12, 24, 24, 72, ...]

  orbitRadii: number[]         // [0, 82, 162, 335, 493, ...]

    orbitAnglesByOrbit: number[][] // precomputed angle table per orbit
  classes: Record<string, TreeClass>

  min_x: number

  max_x: number

  min_y: number

  max_y: number

}



export interface TreeClass {

  name: string

  displayName: string

  integerId: number

  background?: ClassBackground

  startNodeId?: string

  ascendancies: AscendancyClass[]

}

export interface ClassBackground {

  image: string

  x: number

  y: number

  width: number

  height: number

  section?: string

  active?: {

    width: number

    height: number

  }

  bg?: {

    width: number

    height: number

  }

}



export interface AscendancyClass {

  name: string

  displayName?: string

  id?: string

  internalId?: string

  background?: {

    image: string

    x: number

    y: number

    width: number

    height: number

    section?: string

  }

}



// ---- Group ----

export interface TreeGroup {

  id: string

    x: number         // Cartesian X coordinate
    y: number         // Cartesian Y coordinate
  orbits: number[]

    nodes: string[]   // node IDs belonging to this group
}

export interface TreeAssetSize {
  width: number
  height: number
}

export interface TreeNodeTargetSize extends TreeAssetSize {
  effect?: TreeAssetSize
  overlay?: TreeAssetSize
}



// ---- Node Types ----
export type NodeType =

  | 'Normal'

  | 'Notable'

  | 'Keystone'

  | 'ClassStart'

  | 'AscendClassStart'

  | 'Mastery'

  | 'JewelSocket'

  | 'Socket'

  | 'OnlyImage'



// ---- Precomputed Fields ----
export interface TreeNode {
    // Original fields
    id: string            // unique node ID (= skill)
    name: string          // display name
    icon: string          // icon asset key
    stats: string[]       // stat effect descriptions
  type: NodeType



    // Topology
    group: string         // parent group ID
    orbit: number         // orbit layer (0-9)
    orbitIndex: number    // position within orbit


    // Precomputed coordinates (by gen_tree_data.py)
  x: number

  y: number



    // Connections
    out: string[]         // outgoing node IDs (forward)
    connections?: TreeConnection[] // raw connections: ID + orbit metadata
    in: string[]          // incoming node IDs (precomputed reverse edges)


    // Class info
    classesStart?: string[]   // ClassStart: starting class list
    ascendancyName?: string   // AscendClassStart: ascendancy name
  isAscendancyStart?: boolean

  isSwitchable?: boolean

  options?: Record<string, number>



    // Flags
  isMultipleChoice?: boolean

  isMultipleChoiceOption?: boolean

  isJewelSocket?: boolean

  isMastery?: boolean

  masteryEffect?: number

  recipe?: string[]

  reminderText?: string[]

  flavourText?: string[]


    // Visual DDS sprite fields (from tree.json, precomputed by gen_tree_data.py)
    activeEffectImage?: string   // DDS asset for glow effect
    connectionArt?: string       // DDS asset for connection line sprite
  nodeOverlay?: Record<string, string>  // {alloc, path, unalloc} frame names
  targetSize?: TreeNodeTargetSize
  angle?: number
}

export interface TreeConnection {
  id: string
  orbit: number
}

export type ConnectorStateName = 'Normal' | 'Intermediate' | 'Active'

export interface TreeConnectorQuad {
  nodeId1: string
  nodeId2: string
  ascendancyName?: string
  connectionArt: string
  type: string
  texCoords: number[]
  vert: Record<ConnectorStateName, number[]>
}


// ---- Full Tree ----
export interface TreeData {

  version: TreeVersion

  constants: {

    skillsPerOrbit: number[]

    orbitRadii: number[]

    classes: Record<string, TreeClass>

    min_x: number

    max_x: number

    min_y: number

    max_y: number

  }

  groups: Record<string, TreeGroup>

  nodes: Record<string, TreeNode>

    /** additional art info (optional) */
  connectionArt?: Record<string, unknown>

  connectors?: TreeConnectorQuad[]

  /** type-default overlay frames: {Keystone: {alloc,path,unalloc}, ...} */
  nodeOverlay?: Record<string, Record<string, string>>

}

// ---- Saved Build (Phase 16.7) ----
export interface SavedBuild {
  id: string            // uuid
  name: string
  createdAt: string     // ISO date
  updatedAt: string
  treeVersion: string
  selectedClassId: string
  selectedAscendancyId: string
  weaponSetMode: 0 | 1 | 2
  nodeWeaponSets: Record<string, 1 | 2>
  masterySelections: Record<string, string>
  allocatedNodes: string[]
}

