-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Crude Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 4, PhysicalMax = 10, CritChanceBase = 5, AttackRateBase = 1.65, Range = 11, },
	req = { },
}
itemBases["Pict Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 4, PhysicalMax = 16, CritChanceBase = 5, AttackRateBase = 1.7, Range = 11, },
	req = { level = 6, dex = 14, },
}
itemBases["Wolfbone Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicit = "Grants 8 Life per Enemy Hit",
	implicitModTypes = { { "resource", "life", "attack" }, },
	weapon = { PhysicalMin = 7, PhysicalMax = 23, CritChanceBase = 5, AttackRateBase = 1.6, Range = 11, },
	req = { level = 12, dex = 24, },
}
itemBases["Forked Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 10, PhysicalMax = 26, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { level = 16, dex = 31, },
}
itemBases["Plated Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 13, PhysicalMax = 31, CritChanceBase = 5, AttackRateBase = 1.6, Range = 11, },
	req = { level = 22, dex = 41, },
}
itemBases["Edged Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicit = "(15-25)% chance to Blind Enemies on hit",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 38, CritChanceBase = 5, AttackRateBase = 1.7, Range = 11, },
	req = { level = 28, dex = 52, },
}
itemBases["Arced Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, one_hand_weapon = true, onehand = true, vaal_basetype = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 12, PhysicalMax = 46, CritChanceBase = 5, AttackRateBase = 1.65, Range = 11, },
	req = { level = 33, dex = 60, },
}
itemBases["Hooked Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, one_hand_weapon = true, onehand = true, vaal_basetype = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 16, PhysicalMax = 49, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { level = 36, dex = 65, },
}
itemBases["Razorglass Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 23, PhysicalMax = 54, CritChanceBase = 5, AttackRateBase = 1.6, Range = 11, },
	req = { level = 45, dex = 80, },
}
itemBases["Sharktooth Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 25, PhysicalMax = 52, CritChanceBase = 5, AttackRateBase = 1.7, Range = 11, },
	req = { level = 49, dex = 87, },
}
itemBases["Armoured Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 27, PhysicalMax = 63, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { level = 52, dex = 92, },
}
itemBases["Piercing Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 23, PhysicalMax = 68, CritChanceBase = 5, AttackRateBase = 1.6, Range = 11, },
	req = { level = 55, dex = 97, },
}
itemBases["Talon Claw"] = {
	type = "Claw",
	quality = 20,
	socketLimit = 3,
	tags = { claw = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 23, PhysicalMax = 79, CritChanceBase = 5, AttackRateBase = 1.65, Range = 11, },
	req = { level = 65, dex = 114, },
}
