-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Twig Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 12, },
	req = { },
}
itemBases["Woven Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 15, },
	req = { level = 6, int = 11, },
}
itemBases["Antler Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 18, },
	req = { level = 10, int = 17, },
}
itemBases["Engraved Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 22, },
	req = { level = 16, int = 25, },
}
itemBases["Tonal Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 26, },
	req = { level = 22, int = 33, },
}
itemBases["Crystal Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 29, },
	req = { level = 26, int = 38, },
}
itemBases["Voodoo Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 34, },
	req = { level = 33, int = 48, },
}
itemBases["Plumed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 36, },
	req = { level = 36, int = 52, },
}
itemBases["Runed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 42, },
	req = { level = 45, int = 64, },
}
itemBases["Whorl Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 47, },
	req = { level = 51, int = 73, },
}
itemBases["Elegant Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 47, },
	req = { level = 52, int = 74, },
}
itemBases["Attuned Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 51, },
	req = { level = 57, int = 81, },
}
itemBases["Magus Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 56, },
	req = { level = 65, int = 91, },
}
itemBases["Wreath Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 42, },
	req = { level = 45, int = 64, },
}
itemBases["Staghorn Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 45, },
	req = { level = 48, int = 69, },
}
itemBases["Jingling Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 47, },
	req = { level = 51, int = 73, },
}
itemBases["Arrayed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 49, },
	req = { level = 54, int = 77, },
}
itemBases["Cultist Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 52, },
	req = { level = 59, int = 83, },
}
itemBases["Hallowed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 57, },
	req = { level = 61, int = 86, },
}
itemBases["Druidic Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 62, },
	req = { level = 65, int = 91, },
}
itemBases["Leyline Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 71, },
	req = { level = 70, int = 99, },
}
itemBases["Sacred Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 81, },
	req = { level = 75, int = 107, },
}
itemBases["Tasalian Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 91, },
	req = { level = 80, int = 115, },
}
itemBases["Runeforged Twig Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 12, Ward = 12, },
	req = { },
}
itemBases["Runeforged Woven Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 15, Ward = 15, },
	req = { level = 6, int = 11, },
}
itemBases["Runeforged Antler Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 18, Ward = 17, },
	req = { level = 10, int = 17, },
}
itemBases["Runeforged Engraved Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 22, Ward = 22, },
	req = { level = 16, int = 25, },
}
itemBases["Runeforged Tonal Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 26, Ward = 24, },
	req = { level = 22, int = 33, },
}
itemBases["Runeforged Crystal Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 29, Ward = 25, },
	req = { level = 26, int = 38, },
}
itemBases["Runeforged Voodoo Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 34, Ward = 28, },
	req = { level = 33, int = 48, },
}
itemBases["Runeforged Plumed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 36, Ward = 30, },
	req = { level = 36, int = 52, },
}
itemBases["Runeforged Runed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 42, Ward = 32, },
	req = { level = 45, int = 64, },
}
itemBases["Runeforged Whorl Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 47, Ward = 34, },
	req = { level = 51, int = 73, },
}
itemBases["Runeforged Elegant Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { Ward = 146, },
	req = { level = 52, int = 74, },
}
itemBases["Runeforged Attuned Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { Ward = 157, },
	req = { level = 57, int = 81, },
}
itemBases["Runeforged Magus Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { Ward = 176, },
	req = { level = 65, int = 91, },
}
itemBases["Runeforged Arrayed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 41, Ward = 45, },
	req = { level = 54, int = 77, },
}
itemBases["Runeforged Cultist Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 50, Ward = 32, },
	req = { level = 59, int = 83, },
}
itemBases["Runeforged Hallowed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 40, Ward = 58, },
	req = { level = 61, int = 86, },
}
itemBases["Runeforged Druidic Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 51, Ward = 62, },
	req = { level = 65, int = 91, },
}
itemBases["Runeforged Leyline Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 39, Ward = 114, },
	req = { level = 70, int = 99, },
}
itemBases["Runeforged Sacred Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 65, Ward = 53, },
	req = { level = 75, int = 107, },
}
itemBases["Runeforged Tasalian Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 24, Ward = 181, },
	req = { level = 80, int = 115, },
}
itemBases["Runemastered Twig Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 38, Ward = 23, },
	req = { level = 38, int = 54, },
}
itemBases["Runemastered Woven Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 23, Ward = 45, },
	req = { level = 38, int = 54, },
}
itemBases["Runemastered Antler Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 23, Ward = 34, },
	req = { level = 38, int = 54, },
}
itemBases["Runemastered Engraved Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 38, Ward = 45, },
	req = { level = 38, int = 54, },
}
itemBases["Runemastered Tonal Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 19, Ward = 57, },
	req = { level = 38, int = 54, },
}
itemBases["Runemastered Crystal Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, runeforged = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 23, Ward = 47, },
	req = { level = 40, int = 58, },
}
itemBases["Runemastered Voodoo Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 40, Ward = 31, },
	req = { level = 55, int = 78, },
}
itemBases["Runemastered Plumed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, runeforged = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 23, Ward = 106, },
	req = { level = 75, int = 91, },
}
