-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Guarding Arm"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Arm",
	tags = { default = true, },
	implicit = "(8-12)% increased Block chance",
	implicitModTypes = { { "block" }, },
	req = { },
}
itemBases["Combat Arm"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Arm",
	tags = { default = true, },
	implicit = "(6-10)% increased Attack Speed",
	implicitModTypes = { { "attack", "speed" }, },
	req = { },
}
itemBases["Caster Arm"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Arm",
	tags = { default = true, },
	implicit = "(6-10)% increased Cast Speed",
	implicitModTypes = { { "caster_speed", "caster", "speed" }, },
	req = { },
}
itemBases["Decrepifying Arm"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Arm",
	tags = { default = true, },
	implicit = "(12-16)% increased Curse Magnitudes",
	implicitModTypes = { { "caster", "curse" }, },
	req = { },
}
itemBases["Deflective Arm"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Arm",
	tags = { default = true, },
	implicit = "(6-10)% increased Deflection Rating",
	implicitModTypes = { { "defences", "evasion" }, },
	req = { },
}
itemBases["Commanding Arm"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Arm",
	tags = { default = true, },
	implicit = "(15-25)% increased Presence Area of Effect",
	implicitModTypes = { { "aura" }, },
	req = { },
}
itemBases["Evasive Leg"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Leg",
	tags = { default = true, },
	implicit = "(20-30)% increased Evasion Rating",
	implicitModTypes = { { "defences", "evasion" }, },
	req = { },
}
itemBases["Sprinters Leg"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Leg",
	tags = { default = true, },
	implicit = "(6-10)% increased Movement Speed while Sprinting",
	implicitModTypes = { { "speed" }, },
	req = { },
}
itemBases["Sturdy Leg"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Leg",
	tags = { default = true, },
	implicit = "(15-25)% increased Stun Threshold",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Surefooted Leg"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Leg",
	tags = { default = true, },
	implicit = "(5-10)% reduced Movement Speed Penalty from using Skills while moving",
	implicitModTypes = { { "speed" }, },
	req = { },
}
itemBases["Calm Leg"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Leg",
	tags = { default = true, },
	implicit = "(20-30)% increased Mana Regeneration Rate while moving",
	implicitModTypes = { { "resource", "mana" }, },
	req = { },
}
itemBases["Restorative Leg"] = {
	type = "Transcendent Limb",
	subType = "Transcendent Leg",
	tags = { default = true, },
	implicit = "(6-10)% of Damage taken Recouped as Life",
	implicitModTypes = { { "resource", "life" }, },
	req = { },
}
