-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Hardwood Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 5, PhysicalMax = 9, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { },
}
itemBases["Ironhead Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 9, PhysicalMax = 12, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 5, dex = 10, },
}
itemBases["Hunting Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n(15-25)% chance to Maim on Hit",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 10, PhysicalMax = 17, CritChanceBase = 5, AttackRateBase = 1.55, Range = 15, },
	req = { level = 10, str = 9, dex = 17, },
}
itemBases["Winged Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 12, PhysicalMax = 22, CritChanceBase = 5, AttackRateBase = 1.7, Range = 15, },
	req = { level = 16, str = 12, dex = 25, },
}
itemBases["War Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n(25-35)% increased Projectile Speed with this Weapon",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 16, PhysicalMax = 27, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 21, str = 14, dex = 31, },
}
itemBases["Forked Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 13, PhysicalMax = 38, CritChanceBase = 5, AttackRateBase = 1.55, Range = 15, },
	req = { level = 26, str = 17, dex = 38, },
}
itemBases["Barbed Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, vaal_basetype = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\nBleeding you inflict deals Damage (10-20)% faster",
	implicitModTypes = { { "bleed", "physical_damage", "damage", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 38, CritChanceBase = 6, AttackRateBase = 1.5, Range = 15, },
	req = { level = 33, str = 20, dex = 47, },
}
itemBases["Broad Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, vaal_basetype = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n25% increased Melee Strike Range with this weapon",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 32, PhysicalMax = 48, CritChanceBase = 5, AttackRateBase = 1.4, Range = 15, },
	req = { level = 40, str = 26, dex = 55, },
}
itemBases["Crossblade Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, karui_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\nPrevent +(3-7)% of Damage from Deflected Hits",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 25, PhysicalMax = 52, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 45, str = 26, dex = 63, },
}
itemBases["Seaglass Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, karui_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 29, PhysicalMax = 53, CritChanceBase = 7, AttackRateBase = 1.6, Range = 15, },
	req = { level = 51, str = 29, dex = 71, int = 50, },
}
itemBases["Sword Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 30, PhysicalMax = 56, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 52, str = 29, dex = 72, },
}
itemBases["Striking Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 11, PhysicalMax = 45, LightningMin = 11, LightningMax = 45, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 55, str = 31, dex = 76, },
}
itemBases["Helix Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 37, PhysicalMax = 68, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 65, str = 36, dex = 89, },
}
itemBases["Steelhead Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 33, PhysicalMax = 44, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 45, str = 26, dex = 63, },
}
itemBases["Coursing Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n(15-25)% chance to Maim on Hit",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 31, PhysicalMax = 52, CritChanceBase = 5, AttackRateBase = 1.55, Range = 15, },
	req = { level = 48, str = 27, dex = 67, },
}
itemBases["Swift Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n(25-35)% increased Projectile Speed with this Weapon",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 32, PhysicalMax = 53, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 51, str = 29, dex = 71, },
}
itemBases["Branched Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 23, PhysicalMax = 69, CritChanceBase = 5, AttackRateBase = 1.55, Range = 15, },
	req = { level = 54, str = 30, dex = 75, },
}
itemBases["Jagged Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\nBleeding you inflict deals Damage (10-20)% faster",
	implicitModTypes = { { "bleed", "physical_damage", "damage", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 33, PhysicalMax = 61, CritChanceBase = 6, AttackRateBase = 1.5, Range = 15, },
	req = { level = 59, str = 33, dex = 81, },
}
itemBases["Massive Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n25% increased Melee Strike Range with this weapon",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 46, PhysicalMax = 69, CritChanceBase = 5, AttackRateBase = 1.4, Range = 15, },
	req = { level = 62, str = 40, dex = 80, },
}
itemBases["Runeforged Hardwood Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, runeforged = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 24, PhysicalMax = 45, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 40, str = 23, dex = 56, },
}
itemBases["Runeforged Ironhead Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, runeforged = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 40, PhysicalMax = 54, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 38, str = 23, dex = 54, },
}
itemBases["Runemastered Ironhead Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, runeforged = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 94, PhysicalMax = 127, CritChanceBase = 5, AttackRateBase = 1.25, Range = 15, },
	req = { level = 55, str = 31, dex = 76, },
}
itemBases["Runeforged Hunting Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, runeforged = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n(15-25)% chance to Maim on Hit",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 65, PhysicalMax = 108, CritChanceBase = 5, AttackRateBase = 1.55, Range = 15, },
	req = { level = 38, str = 23, dex = 54, },
}
itemBases["Runeforged Winged Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, runeforged = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { LightningMin = 0, LightningMax = 125, CritChanceBase = 5, AttackRateBase = 1.7, Range = 15, },
	req = { level = 40, str = 23, dex = 56, },
}
itemBases["Runeforged War Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, runeforged = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n(25-35)% increased Projectile Speed with this Weapon",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 59, PhysicalMax = 98, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 40, str = 23, dex = 56, },
}
itemBases["Runeforged Forked Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, runeforged = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 8, PhysicalMax = 57, CritChanceBase = 7, AttackRateBase = 1.6, Range = 15, },
	req = { level = 55, str = 31, dex = 76, },
}
itemBases["Runeforged Barbed Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, runeforged = true, spear = true, vaal_basetype = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\nBleeding you inflict deals Damage (10-20)% faster",
	implicitModTypes = { { "bleed", "physical_damage", "damage", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 26, PhysicalMax = 49, FireMin = 51, FireMax = 95, CritChanceBase = 6, AttackRateBase = 1.5, Range = 15, },
	req = { level = 55, str = 31, dex = 76, },
}
itemBases["Orichalcum Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 46, PhysicalMax = 62, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 67, str = 41, dex = 104, },
}
itemBases["Soaring Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 35, PhysicalMax = 65, CritChanceBase = 5, AttackRateBase = 1.7, Range = 15, },
	req = { level = 70, str = 41, dex = 115, },
}
itemBases["Pronged Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 30, PhysicalMax = 89, CritChanceBase = 5, AttackRateBase = 1.55, Range = 15, },
	req = { level = 72, str = 46, dex = 115, },
}
itemBases["Stalking Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n(15-25)% chance to Maim on Hit",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 47, PhysicalMax = 79, CritChanceBase = 5, AttackRateBase = 1.55, Range = 15, },
	req = { level = 77, str = 50, dex = 127, },
}
itemBases["Flying Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n(25-35)% increased Projectile Speed with this Weapon",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 46, PhysicalMax = 77, CritChanceBase = 5, AttackRateBase = 1.6, Range = 15, },
	req = { level = 78, str = 50, dex = 127, },
}
itemBases["Grand Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\n25% increased Melee Strike Range with this weapon",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 56, PhysicalMax = 84, CritChanceBase = 5, AttackRateBase = 1.4, Range = 15, },
	req = { level = 79, str = 68, dex = 109, },
}
itemBases["Spiked Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\nBleeding you inflict deals Damage (10-20)% faster",
	implicitModTypes = { { "bleed", "physical_damage", "damage", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 41, PhysicalMax = 76, CritChanceBase = 6, AttackRateBase = 1.5, Range = 15, },
	req = { level = 77, str = 50, dex = 127, },
}
itemBases["Guardian Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, karui_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw\nPrevent +(3-7)% of Damage from Deflected Hits",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 38, PhysicalMax = 79, CritChanceBase = 5, AttackRateBase = 1.55, Range = 15, },
	req = { level = 75, str = 50, dex = 127, },
}
itemBases["Akoyan Spear"] = {
	type = "Spear",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, karui_basetype = true, one_hand_weapon = true, onehand = true, spear = true, weapon = true, },
	implicit = "Grants Skill: Spear Throw",
	implicitModTypes = { },
	weapon = { PhysicalMin = 39, PhysicalMax = 72, CritChanceBase = 7, AttackRateBase = 1.6, Range = 15, },
	req = { level = 78, str = 50, dex = 127, int = 90, },
}
