-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Ashen Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Firebolt",
	implicitModTypes = { },
	req = { },
}
itemBases["Gelid Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, no_chaos_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Freezing Shards",
	implicitModTypes = { },
	req = { },
}
itemBases["Voltaic Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_physical_spell_mods = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Lightning Bolt",
	implicitModTypes = { },
	req = { },
}
itemBases["Spriggan Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Firebolt",
	implicitModTypes = { },
	req = { level = 11, int = 23, },
}
itemBases["Pyrophyte Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Solar Orb",
	implicitModTypes = { },
	req = { level = 16, int = 31, },
}
itemBases["Chiming Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Sigil of Power",
	implicitModTypes = { },
	req = { level = 25, int = 46, },
}
itemBases["Rending Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Soulrend",
	implicitModTypes = { },
	req = { level = 33, int = 60, },
}
itemBases["Reaping Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Reap",
	implicitModTypes = { },
	req = { level = 38, int = 68, },
}
itemBases["Icicle Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, no_chaos_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Firebolt",
	implicitModTypes = { },
	req = { level = 45, int = 80, },
}
itemBases["Roaring Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Unleash",
	implicitModTypes = { },
	req = { level = 49, int = 87, },
}
itemBases["Paralysing Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_physical_spell_mods = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Enervating Nova",
	implicitModTypes = { },
	req = { level = 52, int = 92, },
}
itemBases["Sanctified Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Consecrate",
	implicitModTypes = { },
	req = { level = 56, int = 99, },
}
itemBases["Dark Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Dark Pact",
	implicitModTypes = { },
	req = { level = 65, int = 114, },
}
itemBases["Ravenous Staff"] = {
	type = "Staff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Feast of Flesh",
	implicitModTypes = { },
	req = { level = 65, int = 114, },
}
itemBases["Permafrost Staff"] = {
	type = "Staff",
	quality = 20,
	hidden = true,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Heart of Ice",
	implicitModTypes = { },
	req = { level = 75, int = 114, },
}
itemBases["Reflecting Staff"] = {
	type = "Staff",
	quality = 20,
	hidden = true,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Mirror of Refraction",
	implicitModTypes = { },
	req = { level = 70, int = 114, },
}
itemBases["Perching Staff"] = {
	type = "Staff",
	quality = 20,
	hidden = true,
	socketLimit = 4,
	tags = { default = true, staff = true, twohand = true, },
	implicit = "Grants Skill: Level (1-20) Spiraling Conspiracy",
	implicitModTypes = { },
	req = { level = 65, int = 114, },
}

itemBases["Wrapped Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, ezomyte_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 7, PhysicalMax = 12, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { },
}
itemBases["Long Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, ezomyte_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "16% increased Melee Strike Range with this weapon",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 9, PhysicalMax = 18, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { dex = 9, },
}
itemBases["Gothic Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, ezomyte_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 16, PhysicalMax = 26, CritChanceBase = 12, AttackRateBase = 1.4, Range = 14, },
	req = { level = 11, dex = 18, int = 9, },
}
itemBases["Crackling Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, maraketh_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 5, PhysicalMax = 22, LightningMin = 1, LightningMax = 35, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 16, dex = 25, int = 12, },
}
itemBases["Crescent Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, maraketh_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 19, PhysicalMax = 39, CritChanceBase = 10, AttackRateBase = 1.5, Range = 14, },
	req = { level = 20, dex = 30, int = 14, },
}
itemBases["Steelpoint Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, maraketh_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 28, PhysicalMax = 51, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 28, dex = 41, int = 18, },
}
itemBases["Slicing Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 29, PhysicalMax = 60, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 33, dex = 47, int = 20, },
}
itemBases["Barrier Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, warstaff = true, weapon = true, },
	implicit = "+(12-18)% to Block chance",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 58, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 37, dex = 52, int = 22, },
}
itemBases["Hefty Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, karui_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "(20-50)% chance to Daze on Hit",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 39, PhysicalMax = 81, CritChanceBase = 10, AttackRateBase = 1.3, Range = 14, },
	req = { level = 45, dex = 63, int = 26, },
}
itemBases["Smooth Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, karui_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 59, PhysicalMax = 79, CritChanceBase = 0, AttackRateBase = 1.5, Range = 14, },
	req = { level = 49, dex = 68, int = 28, },
}
itemBases["Anima Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 47, PhysicalMax = 79, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 52, dex = 72, int = 29, },
}
itemBases["Graceful Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 47, PhysicalMax = 87, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 56, dex = 77, int = 31, },
}
itemBases["Wyrm Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 57, PhysicalMax = 94, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 65, dex = 89, int = 36, },
}
itemBases["Reaching Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "16% increased Melee Strike Range with this weapon",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 72, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 45, dex = 63, int = 26, },
}
itemBases["Barbarous Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 42, PhysicalMax = 71, CritChanceBase = 12, AttackRateBase = 1.4, Range = 14, },
	req = { level = 48, dex = 67, int = 27, },
}
itemBases["Arcing Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 14, PhysicalMax = 55, LightningMin = 1, LightningMax = 75, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 51, dex = 71, int = 29, },
}
itemBases["Waxing Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 39, PhysicalMax = 82, CritChanceBase = 10, AttackRateBase = 1.5, Range = 14, },
	req = { level = 54, dex = 75, int = 30, },
}
itemBases["Bladed Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 45, PhysicalMax = 94, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 59, dex = 81, int = 33, },
}
itemBases["Guardian Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "+(12-18)% to Block chance",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 52, PhysicalMax = 86, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 62, dex = 85, int = 34, },
}
itemBases["Sinister Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 55, PhysicalMax = 91, CritChanceBase = 12, AttackRateBase = 1.4, Range = 14, },
	req = { level = 67, dex = 104, int = 41, },
}
itemBases["Lunar Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 50, PhysicalMax = 103, CritChanceBase = 10, AttackRateBase = 1.5, Range = 14, },
	req = { level = 72, dex = 115, int = 46, },
}
itemBases["Striking Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "16% increased Melee Strike Range with this weapon",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 53, PhysicalMax = 111, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 77, dex = 127, int = 50, },
}
itemBases["Bolting Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 24, PhysicalMax = 97, LightningMin = 1, LightningMax = 100, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 78, dex = 127, int = 50, },
}
itemBases["Aegis Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "+(12-18)% to Block chance",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 58, PhysicalMax = 97, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 79, dex = 127, int = 50, },
}
itemBases["Razor Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 65, PhysicalMax = 108, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 77, dex = 127, int = 50, },
}
itemBases["Skullcrusher Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, karui_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "(20-50)% chance to Daze on Hit",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 59, PhysicalMax = 122, CritChanceBase = 10, AttackRateBase = 1.3, Range = 14, },
	req = { level = 75, dex = 127, int = 50, },
}
itemBases["Dreaming Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	socketLimit = 4,
	tags = { default = true, karui_basetype = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 99, PhysicalMax = 133, CritChanceBase = 0, AttackRateBase = 1.5, Range = 14, },
	req = { level = 78, dex = 127, int = 50, },
}
itemBases["Warding Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	hidden = true,
	socketLimit = 4,
	tags = { default = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "+(30-50) to maximum Runic Ward",
	implicitModTypes = { { "runic_ward" }, },
	weapon = { PhysicalMin = 51, PhysicalMax = 85, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 65, dex = 127, int = 50, },
}
itemBases["Runemastered Warding Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	hidden = true,
	socketLimit = 4,
	tags = { default = true, runeforged = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "+(30-50) to maximum Runic Ward",
	implicitModTypes = { { "runic_ward" }, },
	weapon = { PhysicalMin = 51, PhysicalMax = 85, CritChanceBase = 10, AttackRateBase = 1.6, Range = 14, },
	req = { level = 65, dex = 127, int = 50, },
}
itemBases["Runemastered Warding Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	hidden = true,
	socketLimit = 4,
	tags = { default = true, runeforged = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "+(30-50) to maximum Runic Ward",
	implicitModTypes = { { "runic_ward" }, },
	weapon = { PhysicalMin = 51, PhysicalMax = 85, CritChanceBase = 15, AttackRateBase = 1.4, Range = 14, },
	req = { level = 65, dex = 127, int = 50, },
}
itemBases["Runemastered Warding Quarterstaff"] = {
	type = "Staff",
	subType = "Warstaff",
	quality = 20,
	hidden = true,
	socketLimit = 4,
	tags = { default = true, runeforged = true, two_hand_weapon = true, twohand = true, warstaff = true, weapon = true, },
	implicit = "+(30-50) to maximum Runic Ward",
	implicitModTypes = { { "runic_ward" }, },
	weapon = { PhysicalMin = 85, PhysicalMax = 141, CritChanceBase = 10, AttackRateBase = 1.4, Range = 14, },
	req = { level = 65, dex = 127, int = 50, },
}
