-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Changeling Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, ezomyte_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 9, PhysicalMax = 15, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { },
}
itemBases["Nettle Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, ezomyte_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 12, PhysicalMax = 20, CritChanceBase = 11, AttackRateBase = 1.25, Range = 12, },
	req = { level = 5, str = 9, int = 8, },
}
itemBases["Cinderbark Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, ezomyte_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "(50-80)% increased Flammability Magnitude",
	implicitModTypes = { { "elemental", "fire", "ailment" }, },
	weapon = { PhysicalMin = 12, PhysicalMax = 25, FireMin = 5, FireMax = 10, CritChanceBase = 8, AttackRateBase = 1.2, Range = 12, },
	req = { level = 10, str = 15, int = 11, },
}
itemBases["Familial Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "Minions deal (30-50)% increased Damage",
	implicitModTypes = { { "minion_damage", "damage", "minion" }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 34, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 16, str = 21, int = 16, },
}
itemBases["Frenzied Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 23, PhysicalMax = 38, CritChanceBase = 8, AttackRateBase = 1.4, Range = 12, },
	req = { level = 22, str = 28, int = 20, },
}
itemBases["Primal Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "+(14-18)% to Block chance",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 31, PhysicalMax = 46, CritChanceBase = 9, AttackRateBase = 1.3, Range = 12, },
	req = { level = 28, str = 34, int = 25, },
}
itemBases["Rabid Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicit = "+(7-10) to Maximum Rage",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 31, PhysicalMax = 58, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 34, str = 40, int = 29, },
}
itemBases["Vicious Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 43, PhysicalMax = 71, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 40, str = 47, int = 34, },
}
itemBases["Voltfang Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, karui_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "(20-30)% increased Magnitude of Shock you inflict",
	implicitModTypes = { { "elemental", "lightning", "ailment" }, },
	weapon = { PhysicalMin = 16, PhysicalMax = 91, LightningMin = 6, LightningMax = 39, CritChanceBase = 8, AttackRateBase = 1.3, Range = 12, },
	req = { level = 46, str = 53, int = 38, },
}
itemBases["Lumbering Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, karui_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 71, PhysicalMax = 107, CritChanceBase = 5, AttackRateBase = 1.1, Range = 12, },
	req = { level = 52, str = 60, int = 43, },
}
itemBases["Roaring Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "+(7-10) to Maximum Rage",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 57, PhysicalMax = 96, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 58, str = 66, int = 47, },
}
itemBases["Wingbeat Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 45, PhysicalMax = 83, CritChanceBase = 7, AttackRateBase = 1.45, Range = 12, },
	req = { level = 65, str = 74, int = 52, },
}
itemBases["Condemned Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "(10-20)% increased Effect of your Mark Skills",
	implicitModTypes = { { "caster", "curse" }, },
	weapon = { PhysicalMin = 68, PhysicalMax = 113, CritChanceBase = 9, AttackRateBase = 1.25, Range = 12, },
	req = { level = 65, str = 74, int = 52, },
}
itemBases["Howling Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "+(14-18)% to Block chance",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 52, PhysicalMax = 78, CritChanceBase = 9, AttackRateBase = 1.3, Range = 12, },
	req = { level = 55, str = 63, int = 45, },
}
itemBases["Fury Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicit = "+(7-10) to Maximum Rage",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 49, PhysicalMax = 91, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 59, str = 67, int = 48, },
}
itemBases["Cruel Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 62, PhysicalMax = 103, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 63, str = 72, int = 51, },
}
itemBases["Runeforged Changeling Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, ezomyte_basetype = true, runeforged = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 91, PhysicalMax = 151, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 38, str = 45, int = 32, },
}
itemBases["Runeforged Nettle Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, ezomyte_basetype = true, runeforged = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 51, PhysicalMax = 86, CritChanceBase = 11, AttackRateBase = 1.25, Range = 12, },
	req = { level = 38, str = 45, int = 32, },
}
itemBases["Runemastered Nettle Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, ezomyte_basetype = true, runeforged = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 68, PhysicalMax = 114, CritChanceBase = 11, AttackRateBase = 1.25, Range = 12, },
	req = { level = 55, str = 63, int = 45, },
}
itemBases["Runeforged Familial Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, runeforged = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "Minions deal (30-50)% increased Damage",
	implicitModTypes = { { "minion_damage", "damage", "minion" }, },
	weapon = { PhysicalMin = 54, PhysicalMax = 91, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 38, str = 45, int = 32, },
}
itemBases["Runemastered Familial Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, runeforged = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "Minions deal (51-100)% increased Damage",
	implicitModTypes = { { "minion_damage", "damage", "minion" }, },
	weapon = { PhysicalMin = 73, PhysicalMax = 122, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 55, str = 63, int = 45, },
}
itemBases["Runeforged Vicious Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, runeforged = true, talisman = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 123, PhysicalMax = 205, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 65, str = 74, int = 52, },
}
itemBases["Spiny Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, ezomyte_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 60, PhysicalMax = 99, CritChanceBase = 11, AttackRateBase = 1.25, Range = 12, },
	req = { level = 67, str = 86, int = 65, },
}
itemBases["Ashbark Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, ezomyte_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "(50-80)% increased Flammability Magnitude",
	implicitModTypes = { { "elemental", "fire", "ailment" }, },
	weapon = { PhysicalMin = 50, PhysicalMax = 105, FireMin = 21, FireMax = 45, CritChanceBase = 8, AttackRateBase = 1.2, Range = 12, },
	req = { level = 72, str = 94, int = 67, },
}
itemBases["Fang Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "Minions deal (30-50)% increased Damage",
	implicitModTypes = { { "minion_damage", "damage", "minion" }, },
	weapon = { PhysicalMin = 70, PhysicalMax = 116, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 77, str = 89, int = 68, },
}
itemBases["Fungal Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 59, PhysicalMax = 98, CritChanceBase = 8, AttackRateBase = 1.4, Range = 12, },
	req = { level = 78, str = 96, int = 70, },
}
itemBases["Alpha Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, maraketh_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "+(14-18)% to Block chance",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 63, PhysicalMax = 94, CritChanceBase = 9, AttackRateBase = 1.3, Range = 12, },
	req = { level = 75, str = 98, int = 72, },
}
itemBases["Maji Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicit = "+(7-10) to Maximum Rage",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 61, PhysicalMax = 114, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 79, str = 100, int = 67, },
}
itemBases["Wildwood Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, talisman = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 67, PhysicalMax = 112, CritChanceBase = 8, AttackRateBase = 1.25, Range = 12, },
	req = { level = 70, str = 98, int = 72, },
}
itemBases["Thunder Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, karui_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "(20-30)% increased Magnitude of Shock you inflict",
	implicitModTypes = { { "elemental", "lightning", "ailment" }, },
	weapon = { PhysicalMin = 23, PhysicalMax = 130, LightningMin = 9, LightningMax = 56, CritChanceBase = 8, AttackRateBase = 1.3, Range = 12, },
	req = { level = 77, str = 102, int = 72, },
}
itemBases["Jade Talisman"] = {
	type = "Talisman",
	quality = 20,
	tags = { default = true, karui_basetype = true, talisman = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 101, PhysicalMax = 151, CritChanceBase = 5, AttackRateBase = 1.1, Range = 12, },
	req = { level = 78, str = 109, int = 65, },
}
