-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Withered Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { },
}
itemBases["Bone Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Bone Blast",
	implicitModTypes = { },
	req = { },
}
itemBases["Attuned Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Mana Drain",
	implicitModTypes = { },
	req = { },
}
itemBases["Siphoning Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Power Siphon",
	implicitModTypes = { },
	req = { level = 11, int = 23, },
}
itemBases["Volatile Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Volatile Dead",
	implicitModTypes = { },
	req = { level = 16, int = 31, },
}
itemBases["Galvanic Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_physical_spell_mods = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Galvanic Field",
	implicitModTypes = { },
	req = { level = 25, int = 46, },
}
itemBases["Acrid Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Decompose",
	implicitModTypes = { },
	req = { level = 33, int = 60, },
}
itemBases["Offering Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, no_chaos_spell_mods = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Exsanguinate",
	implicitModTypes = { },
	req = { level = 38, int = 68, },
}
itemBases["Frigid Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, no_chaos_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { level = 45, int = 80, },
}
itemBases["Torture Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { level = 49, int = 87, },
}
itemBases["Critical Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Chaos Bolt",
	implicitModTypes = { },
	req = { level = 52, int = 92, },
}
itemBases["Primordial Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, no_cold_spell_mods = true, no_fire_spell_mods = true, no_lightning_spell_mods = true, no_physical_spell_mods = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Wither",
	implicitModTypes = { },
	req = { level = 56, int = 99, },
}
itemBases["Dueling Wand"] = {
	type = "Wand",
	quality = 20,
	socketLimit = 3,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Spellslinger",
	implicitModTypes = { },
	req = { level = 65, int = 114, },
}
itemBases["Twisted Wand"] = {
	type = "Wand",
	quality = 20,
	hidden = true,
	socketLimit = 3,
	tags = { default = true, onehand = true, wand = true, },
	implicit = "Grants Skill: Level (1-20) Coiling Bolts",
	implicitModTypes = { },
	req = { level = 65, int = 114, },
}
itemBases["Runic Fork"] = {
	type = "Wand",
	quality = 20,
	hidden = true,
	socketLimit = 3,
	tags = { default = true, onehand = true, wand = true, },
	implicitModTypes = { },
	req = { level = 65, int = 114, },
}
itemBases["Runemastered Runic Fork"] = {
	type = "Wand",
	quality = 20,
	hidden = true,
	socketLimit = 3,
	tags = { default = true, onehand = true, runeforged = true, wand = true, },
	implicit = "(30-50)% chance for Spell Skills to fire 2 additional Projectiles",
	implicitModTypes = { { "caster" }, },
	req = { level = 65, int = 114, },
}
itemBases["Runemastered Runic Fork"] = {
	type = "Wand",
	quality = 20,
	hidden = true,
	socketLimit = 3,
	tags = { default = true, onehand = true, runeforged = true, wand = true, },
	implicit = "(30-50)% increased Mana Regeneration Rate",
	implicitModTypes = { { "resource", "mana" }, },
	req = { level = 65, int = 114, },
}
itemBases["Runemastered Runic Fork"] = {
	type = "Wand",
	quality = 20,
	hidden = true,
	socketLimit = 3,
	tags = { default = true, onehand = true, runeforged = true, wand = true, },
	implicit = "+300 to maximum Runic Ward",
	implicitModTypes = { { "runic_ward" }, },
	req = { level = 65, int = 114, },
}
