local out = io.open("../Data/Essence.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Item data (c) Grinding Gear Games\n\nreturn {\n')
for essence in dat("Essences"):Rows() do
	if essence.BaseItemType.Id:match("Essence(.+)") then
		out:write('\t["', essence.BaseItemType.Id, '"] = { name = "', essence.BaseItemType.Name, '", ')
		out:write('type = "', essence.BaseItemType.Id:match("Essence(.+)"), '", tierLevel = ', essence.DropLevel[1], ', ')
		out:write('mods = { ')
		for _, essenceMod in ipairs(dat("EssenceMods"):GetRowList("Essence", essence)) do
			for _, itemClass in ipairs(essenceMod.TargetItemCategory.ItemClasses) do
				local mod = essenceMod.Mod1 or essenceMod.Mod2
				if mod ~= nil then
					out:write('["', itemClass.Id, '"] = "', mod.Id, '", ')
				end
			end
		end
		out:write('}, },\n')
	end
end
out:write('}')
out:close()

print("Essences exported.")
