if not loadStatFile then
	dofile("statdesc.lua")
end
local statDescriptions = getStatDescriptors("stat_descriptions.csd")
loadStatFile("stat_descriptions.csd")

-- not comprehensive. see mod domains table in export tool and enums.lua
local Domains = {
	GenericMod = 1,
	FlaskCharm = 2,
	Jewel = 11,
	UniqueJewel = 22,
	Veiled = 28,
	-- not actually present on the table, but still referenced by mods
	IncursionLimb = 37,
}

local GenTypes = {
	Prefix = 1,
	Suffix = 2,
	-- includes both implicit mods and unique explicit mods
	Intrinsic = 3,
	Corruption = 5,
}

function table.containsId(table, element)
	for _, value in pairs(table) do
		if value.Id == element then
			return true
		end
	end
	return false
end

-- used for calculating the hash field of a stat
local GGG_STAT_HASH32_SEED = 0xC58F1A7B
-- used for calculating the trade hash from stat hash fields
local GGG_TRADE_SEED = 0x02312233
---@param stats string[]
---@return integer
local function hashStats(stats)
	local statHashes = ""
	for _, statName in ipairs(stats) do
		local newHash = intToBytes(murmurHash2(statName, GGG_STAT_HASH32_SEED))
		statHashes = statHashes..newHash
	end
	return murmurHash2(statHashes, GGG_TRADE_SEED)
end

local whiteListStat = {
	["dummy_stat_display_nothing"] = true,
}

local lifeFlaskModTypes, manaFlaskModTypes = unpack(LoadModule("Scripts/ScriptResources/FlaskModWeights"))
local strJewelTypes, dexJewelTypes, intJewelTypes = unpack(LoadModule("Scripts/ScriptResources/JewelModWeights"))
local corruptedModTypes = LoadModule("Scripts/ScriptResources/CorruptedModWeights")
local function writeMods(outName, condFunc)
	local out = io.open(outName, "w")
	out:write('-- This file is automatically generated, do not edit!\n')
	out:write('-- Item data (c) Grinding Gear Games\n\nreturn {\n')
	for mod in dat("Mods"):Rows() do
		if condFunc(mod) then
			local stats, orders, missing = describeMod(mod)
			if missing[1] then
				local printHeader = true
				for k, _ in pairs(missing) do
					if k ~= 1 and not whiteListStat[k] then
						if printHeader then
							printHeader = false
							ConPrintf("====================================")
							ConPrintf("Mod '" .. mod.Id .. "' is missing stats:")
						end
						ConPrintf('%s', k)
					end
				end
			end
			if #orders > 0 then
				out:write('\t["', mod.Id, '"] = { ')
				if mod.GenerationType == GenTypes.Prefix then
					out:write('type = "Prefix", ')
				elseif mod.GenerationType == GenTypes.Suffix then
					out:write('type = "Suffix", ')
				elseif mod.GenerationType == GenTypes.Intrinsic then
					if mod.Id:match("SpecialCorruption") then
						out:write('type = "SpecialCorrupted", ')
					end
				elseif mod.GenerationType == GenTypes.Corruption then
					out:write('type = "Corrupted", ')
				end
				out:write('affix = "', mod.Name, '", ')
				for index, value in pairs(mod.Family) do
					if string.find(value.Id, "LocalDisplayNearbyEnemy") and #stats > index and #orders > index then
						table.remove(stats, index)
						table.remove(orders, index)
						break
					end
				end
				out:write('"', table.concat(stats, '", "'), '", ')
				out:write('statOrder = { ', table.concat(orders, ', '), ' }, ')
				out:write('level = ', mod.Level, ', group = "', mod.Type.Id, '", ')
				out:write('weightKey = { ')
				for _, tag in ipairs(mod.SpawnTags) do
					out:write('"', tag.Id, '", ')
				end
				out:write('}, ')
				out:write('weightVal = { ', table.concat(mod.SpawnWeight, ', '), ' }, ')
				if mod.GenerationWeightTags[1] then
					-- make large clusters only have 1 notable suffix
					if mod.GenerationType == GenTypes.Suffix and mod.Tags[1] and outName == "../Data/ModJewelCluster.lua" and mod.Tags[1].Id == "has_affliction_notable" then
						out:write('weightMultiplierKey = { "has_affliction_notable2", ')
						for _, tag in ipairs(mod.GenerationWeightTags) do
							out:write('"', tag.Id, '", ')
						end
						out:write('}, ')
						out:write('weightMultiplierVal = { 0, ', table.concat(mod.GenerationWeightValues, ', '), ' }, ')
						if mod.Tags[1] then
							out:write('tags = { "has_affliction_notable2", ')
							for _, tag in ipairs(mod.Tags) do
								out:write('"', tag.Id, '", ')
							end
							out:write('}, ')
						end
					else
						out:write('weightMultiplierKey = { ')
						for _, tag in ipairs(mod.GenerationWeightTags) do
							out:write('"', tag.Id, '", ')
						end
						out:write('}, ')
						out:write('weightMultiplierVal = { ', table.concat(mod.GenerationWeightValues, ', '), ' }, ')
						if mod.Tags[1] then
							out:write('tags = { ')
							for _, tag in ipairs(mod.Tags) do
								out:write('"', tag.Id, '", ')
							end
							out:write('}, ')
						end
					end
				end
				out:write('modTags = { ', stats.modTags, ' }, ')
				if mod.NodeType ~= 3 then
					out:write('nodeType = ', mod.NodeType, ', ')
				end

				local tradeHashes = {}
				local statsHashed = {}
				local isTinctureMod = (mod.Domain == Domains.Tincture) and
					(mod.GenerationType == GenTypes.Prefix
						or mod.GenerationType == GenTypes.Suffix)
				for statIdx = 1, 6 do
					local currentStats = {}
					local stat = mod["Stat" .. statIdx]
					if not stat then
						break
					end
					-- some stats are related to other stats, and should be
					-- hashed with them. we don't want to hash e.g. the lower
					-- and upper range of # to # damage modifiers separately.
					if statsHashed[stat.Id] then
						goto innerContinue
					end

					-- tincture stat descriptions are in a separate file
					local statEntry
					if isTinctureMod then
						statEntry = tinctureStatDescriptions[stat.Id] and tinctureStatDescriptions[stat.Id]
					else
						statEntry = statDescriptions[stat.Id] and statDescriptions[stat.Id]
					end

					-- skip stats that are missing fields. these are most likely
					-- hidden stats or e.g. map stats
					if not statEntry or not statEntry.stats or not statEntry[1] then
						goto innerContinue
					end

					-- match stats to the stat values on the mod and save them
					-- as they're used to describe the stat
					local currentStats = {}
					for _, statId in ipairs(statEntry.stats) do
						for statIdx = 1, 6 do
							if mod["Stat" .. statIdx] and mod["Stat" .. statIdx].Id == statId then
								currentStats[statId] = {
									min = mod["Stat" .. statIdx .. "Value"][1],
									max = mod["Stat" .. statIdx .. "Value"][2]
								}
							end
						end
					end

					-- radius jewel stats are slightly unique in that they use
					-- the same stat as regular jewel mods. this means the
					-- description will not include the also grant: prefix
					local stats = copyTable(statEntry.stats)
					-- radius jewels lack a proper stat descriptor and so we add it manually
					local prefix
					-- radius jewel mods:
					-- notable
					if mod.NodeType == 2 then
						table.insert(stats, "local_jewel_mod_stats_added_to_notable_passives")
						prefix = "Notable Passive Skills in Radius also grant "
					-- small
					elseif mod.NodeType and mod.NodeType == 1 then
						table.insert(stats, "local_jewel_mod_stats_added_to_small_passives")
						prefix = "Small Passive Skills in Radius also grant "
					end


					local description, _, _ = describeStats(currentStats)

					if prefix then
						for i, v in ipairs(description or {}) do
							description[i] = prefix..v
						end
					end

					local tradeHash = hashStats(stats)
					tradeHashes[tradeHash] = description
					::innerContinue::
				end
				out:write("tradeHashes = { ")
				for hash, desc in pairs(tradeHashes) do
					local descriptionLines = '"' .. table.concat(desc, '", "') .. '"'
					out:write(string.format('[%d] = { %s }, ', hash, descriptionLines))
				end
				out:write('} ')
				out:write('},\n')
			else
				print("Mod '" .. mod.Id .. "' has no stats")
			end
		end
		::continue::
	end
	out:write('}')
	out:close()
end

writeMods("../Data/ModItem.lua", function(mod)
	return mod.Domain == Domains.GenericMod and
		(mod.GenerationType == GenTypes.Prefix or mod.GenerationType == GenTypes.Suffix)
		and (mod.Family[1] and mod.Family[1].Id ~= "AuraBonus" or not mod.Family[1]) and (not mod.Id:match("Cowards")) and
		not mod.Id:match("Master")
end)
writeMods("../Data/ModCorrupted.lua", function(mod)
	return (mod.Domain == Domains.Jewel or mod.Domain == Domains.GenericMod) and
	(mod.GenerationType == GenTypes.Intrinsic and mod.Id:match("SpecialCorruption") or mod.GenerationType == GenTypes.Corruption)
end)
writeMods("../Data/ModFlask.lua", function(mod)
	return mod.Domain == Domains.FlaskCharm and
	(mod.GenerationType == GenTypes.Prefix or mod.GenerationType == GenTypes.Suffix) and mod.Id:match("^Flask")
end)
writeMods("../Data/ModCharm.lua", function(mod)
	return mod.Domain == Domains.FlaskCharm and ((mod.GenerationType == GenTypes.Prefix and mod.Id:match("^Charm"))
		or (mod.GenerationType == GenTypes.Suffix and not mod.Id:match("Immunity")))
end)
writeMods("../Data/ModJewel.lua", function(mod)
	return (mod.Domain == Domains.Jewel and (mod.GenerationType == GenTypes.Prefix or mod.GenerationType == GenTypes.Suffix)) or
	(mod.Domain == Domains.FlaskCharm1 and mod.GenerationType == GenTypes.Intrinsic)
end)
writeMods("../Data/ModIncursionLimb.lua", function(mod)
	return (mod.Domain == Domains.IncursionLimb and mod.GenerationType == GenTypes.Intrinsic)
end)
writeMods("../Data/ModItemExclusive.lua",
	-- contains primarily uniques and items implicits but also other mods only available on a single base or unique.
	function(mod)
		return (mod.Domain == Domains.GenericMod or mod.Domain == Domains.FlaskCharm or mod.Domain == Domains.Jewel or mod.Domain == Domains.UniqueJewel) and
			mod.GenerationType == GenTypes.Intrinsic
			and (mod.Family[1] and mod.Family[1].Id ~= "AuraBonus" or not mod.Family[1])
			and not mod.Id:match("^Synthesis") and not mod.Id:match("Royale") and not mod.Id:match("Cowards") and
			not mod.Id:match("Map") and not mod.Id:match("Ultimatum") and not mod.Id:match("SpecialCorruption")
	end)
writeMods("../Data/ModVeiled.lua", function(mod)
	return mod.Domain == Domains.Veiled and not mod.Id:match("Map")
end)

print("Mods exported.")
